// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_team_join_apply_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_team_join_apply_type.proto</summary>
  public static partial class EnumETeamJoinApplyTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_team_join_apply_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumETeamJoinApplyTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFlbnVtX2VfdGVhbV9qb2luX2FwcGx5X3R5cGUucHJvdG8SBnpwcm90bypQ",
            "ChJFVGVhbUpvaW5BcHBseVR5cGUSHgoaRVRlYW1Kb2luQXBwbHlUeXBlUGVy",
            "c29uYWwQABIaChZFVGVhbUpvaW5BcHBseVR5cGVUZWFtEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ETeamJoinApplyType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ETeamJoinApplyType {
    [pbr::OriginalName("ETeamJoinApplyTypePersonal")] Personal = 0,
    [pbr::OriginalName("ETeamJoinApplyTypeTeam")] Team = 1,
  }

  #endregion

}

#endregion Designer generated code
