// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_team_join_condition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_team_join_condition.proto</summary>
  public static partial class EnumETeamJoinConditionReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_team_join_condition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumETeamJoinConditionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBlbnVtX2VfdGVhbV9qb2luX2NvbmRpdGlvbi5wcm90bxIGenByb3RvKn4K",
            "EkVUZWFtSm9pbkNvbmRpdGlvbhIaChZFVGVhbUpvaW5Db25kaXRpb25OdWxs",
            "EAASIgoeRVRlYW1Kb2luQ29uZGl0aW9uQWJpbGl0eVNjb3JlEAESKAokRVRl",
            "YW1Kb2luQ29uZGl0aW9uU2Vhc29uQWJpbGl0eVNjb3JlEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.ETeamJoinCondition), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ETeamJoinCondition {
    [pbr::OriginalName("ETeamJoinConditionNull")] Null = 0,
    [pbr::OriginalName("ETeamJoinConditionAbilityScore")] AbilityScore = 1,
    [pbr::OriginalName("ETeamJoinConditionSeasonAbilityScore")] SeasonAbilityScore = 2,
  }

  #endregion

}

#endregion Designer generated code
