// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_e_function_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from enum_e_function_type.proto</summary>
  public static partial class EnumEFunctionTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_e_function_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumEFunctionTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChplbnVtX2VfZnVuY3Rpb25fdHlwZS5wcm90bxIGenByb3RvKtUICg1FRnVu",
            "Y3Rpb25UeXBlEhQKEEZ1bmN0aW9uVHlwZU51bGwQABIiChxGdW5jdGlvblR5",
            "cGVQaWNrdXBQcm9mZXNzaW9uEIyOBhIbChVGdW5jdGlvblR5cGVDaGVja05h",
            "bWUQ944GEh0KF0Z1bmN0aW9uVHlwZU1vbnN0ZXJIdW50EMSTBhIbChVGdW5j",
            "dGlvblR5cGVUZWFtVm9pY2UQkJUGEiAKGkZ1bmN0aW9uVHlwZVRlYW1Wb2lj",
            "ZVNwZWFrEJGVBhIaChRGdW5jdGlvblR5cGVTZXRDb2xvchDzlQYSFgoQRnVu",
            "Y3Rpb25UeXBlQ2hhdBDUnQYSHwoZRnVuY3Rpb25UeXBlSG9tZUJsdWVwcmlu",
            "dBDzoAYSIgocRnVuY3Rpb25UeXBlUGFpbkhvbWVTdWJNb2RlbBD3oAYSGgoU",
            "RnVuY3Rpb25UeXBlUGFpbkhvbWUQ+KAGEhYKEEZ1bmN0aW9uVHlwZVJpZGUQ",
            "kKMGEh4KGEZ1bmN0aW9uVHlwZVByb2Zlc3Npb25MdhCJrgYSHQoXRnVuY3Rp",
            "b25UeXBlSG9tZVJlY3ljbGUQ+bwGEiQKHkZ1bmN0aW9uVHlwZUJsYWNrTWFy",
            "a2V0UmVjeWNsZRD9vAYSHgoYRnVuY3Rpb25UeXBlRmFudGFzeUF0bGFzEL6e",
            "DBIfChlGdW5jdGlvblR5cGVBb3lpU2tpbGxTd2FwEL+eDBIfChlGdW5jdGlv",
            "blR5cGVMaW5lYXJEdW5nZW9uEMSoEhIjCh1GdW5jdGlvblR5cGVIZXJvRHVu",
            "Z2Vvbk5vcm1hbBCpqRISJgogRnVuY3Rpb25UeXBlSGVyb0R1bmdlb25DaGFs",
            "bGVuZ2UQqqkSEh4KGEZ1bmN0aW9uVHlwZVBsYW5ldE1lbW9yeRCNqhISGwoV",
            "RnVuY3Rpb25UeXBlVW5pb25IdW50ELfDHhIZChNGdW5jdGlvblR5cGVQZXRN",
            "YWluEMzEHhIbChVGdW5jdGlvblR5cGVQZXRTdW1tb24QzcQeEh0KF0Z1bmN0",
            "aW9uVHlwZUp1bXBDbGltYlVwEJnJHhIaChRGdW5jdGlvblR5cGVUcmVhc3Vy",
            "ZRDRyx4SHAoWRnVuY3Rpb25UeXBlQ2hhbmdlTmFtZRDG3SoSHAoWRnVuY3Rp",
            "b25UeXBlV29ybGRFdmVudBDk6jASHQoXRnVuY3Rpb25UeXBlU2Vhc29uUXVl",
            "c3QQ9e0wEhwKFkZ1bmN0aW9uVHlwZVNlYXNvblJhbmsQ9+0wEiMKHUZ1bmN0",
            "aW9uVHlwZVNlYXNvbkFjaGlldmVtZW50EPjtMBIiChxGdW5jdGlvblR5cGVT",
            "ZWFzb25BY3RpdmF0aW9uEPntMBItCidGdW5jdGlvblR5cGVFeGNoYW5nZURp",
            "YW1vbmRUb1NpbHZlckNvaW4Qve8wEi0KJ0Z1bmN0aW9uVHlwZUV4Y2hhbmdl",
            "RGlhbW9uZFRvQ29wcGVyQ29pbhC+7zBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zproto.EFunctionType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EFunctionType {
    [pbr::OriginalName("FunctionTypeNull")] FunctionTypeNull = 0,
    [pbr::OriginalName("FunctionTypePickupProfession")] FunctionTypePickupProfession = 100108,
    [pbr::OriginalName("FunctionTypeCheckName")] FunctionTypeCheckName = 100215,
    [pbr::OriginalName("FunctionTypeMonsterHunt")] FunctionTypeMonsterHunt = 100804,
    [pbr::OriginalName("FunctionTypeTeamVoice")] FunctionTypeTeamVoice = 101008,
    [pbr::OriginalName("FunctionTypeTeamVoiceSpeak")] FunctionTypeTeamVoiceSpeak = 101009,
    [pbr::OriginalName("FunctionTypeSetColor")] FunctionTypeSetColor = 101107,
    [pbr::OriginalName("FunctionTypeChat")] FunctionTypeChat = 102100,
    [pbr::OriginalName("FunctionTypeHomeBlueprint")] FunctionTypeHomeBlueprint = 102515,
    [pbr::OriginalName("FunctionTypePainHomeSubModel")] FunctionTypePainHomeSubModel = 102519,
    [pbr::OriginalName("FunctionTypePainHome")] FunctionTypePainHome = 102520,
    [pbr::OriginalName("FunctionTypeRide")] FunctionTypeRide = 102800,
    [pbr::OriginalName("FunctionTypeProfessionLv")] FunctionTypeProfessionLv = 104201,
    [pbr::OriginalName("FunctionTypeHomeRecycle")] FunctionTypeHomeRecycle = 106105,
    [pbr::OriginalName("FunctionTypeBlackMarketRecycle")] FunctionTypeBlackMarketRecycle = 106109,
    [pbr::OriginalName("FunctionTypeFantasyAtlas")] FunctionTypeFantasyAtlas = 200510,
    [pbr::OriginalName("FunctionTypeAoyiSkillSwap")] FunctionTypeAoyiSkillSwap = 200511,
    [pbr::OriginalName("FunctionTypeLinearDungeon")] FunctionTypeLinearDungeon = 300100,
    [pbr::OriginalName("FunctionTypeHeroDungeonNormal")] FunctionTypeHeroDungeonNormal = 300201,
    [pbr::OriginalName("FunctionTypeHeroDungeonChallenge")] FunctionTypeHeroDungeonChallenge = 300202,
    [pbr::OriginalName("FunctionTypePlanetMemory")] FunctionTypePlanetMemory = 300301,
    [pbr::OriginalName("FunctionTypeUnionHunt")] FunctionTypeUnionHunt = 500151,
    [pbr::OriginalName("FunctionTypePetMain")] FunctionTypePetMain = 500300,
    [pbr::OriginalName("FunctionTypePetSummon")] FunctionTypePetSummon = 500301,
    [pbr::OriginalName("FunctionTypeJumpClimbUp")] FunctionTypeJumpClimbUp = 500889,
    [pbr::OriginalName("FunctionTypeTreasure")] FunctionTypeTreasure = 501201,
    [pbr::OriginalName("FunctionTypeChangeName")] FunctionTypeChangeName = 700102,
    [pbr::OriginalName("FunctionTypeWorldEvent")] FunctionTypeWorldEvent = 800100,
    [pbr::OriginalName("FunctionTypeSeasonQuest")] FunctionTypeSeasonQuest = 800501,
    [pbr::OriginalName("FunctionTypeSeasonRank")] FunctionTypeSeasonRank = 800503,
    [pbr::OriginalName("FunctionTypeSeasonAchievement")] FunctionTypeSeasonAchievement = 800504,
    [pbr::OriginalName("FunctionTypeSeasonActivation")] FunctionTypeSeasonActivation = 800505,
    [pbr::OriginalName("FunctionTypeExchangeDiamondToSilverCoin")] FunctionTypeExchangeDiamondToSilverCoin = 800701,
    [pbr::OriginalName("FunctionTypeExchangeDiamondToCopperCoin")] FunctionTypeExchangeDiamondToCopperCoin = 800702,
  }

  #endregion

}

#endregion Designer generated code
