// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_dungeon_leader_board_vote.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_dungeon_leader_board_vote.proto</summary>
  public static partial class StruDungeonLeaderBoardVoteReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_dungeon_leader_board_vote.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruDungeonLeaderBoardVoteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRzdHJ1X2R1bmdlb25fbGVhZGVyX2JvYXJkX3ZvdGUucHJvdG8SBnpwcm90",
            "bxorc3RydV9kdW5nZW9uX2xlYWRlcl9ib2FyZF92b3RlX21lbWJlci5wcm90",
            "bxoVc3RydV9kaXJ0eV9tYXNrLnByb3RvIt0CChZEdW5nZW9uTGVhZGVyQm9h",
            "cmRWb3RlEiQKDWxlYWRlckJvYXJkSWQYASABKAVSDWxlYWRlckJvYXJkSWQS",
            "JAoNdm90ZUNvdW50ZXJJZBgCIAEoBVINdm90ZUNvdW50ZXJJZBIYCgdjYW5W",
            "b3RlGAMgASgIUgdjYW5Wb3RlEhQKBXN0YXRlGAQgASgFUgVzdGF0ZRIqChBi",
            "bG9ja2VkTWVtYmVySWRzGAUgAygDUhBibG9ja2VkTWVtYmVySWRzEkUKB21l",
            "bWJlcnMYBiADKAsyKy56cHJvdG8uRHVuZ2VvbkxlYWRlckJvYXJkVm90ZS5N",
            "ZW1iZXJzRW50cnlSB21lbWJlcnMaVAoMTWVtYmVyc0VudHJ5EgsKA2tleRgB",
            "IAEoAxIzCgV2YWx1ZRgCIAEoCzIkLnpwcm90by5EdW5nZW9uTGVhZGVyQm9h",
            "cmRWb3RlTWVtYmVyOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruDungeonLeaderBoardVoteMemberReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.DungeonLeaderBoardVote), global::Zproto.DungeonLeaderBoardVote.Parser, new[]{ "LeaderBoardId", "VoteCounterId", "CanVote", "State", "BlockedMemberIds", "Members" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DungeonLeaderBoardVote : pb::IMessage<DungeonLeaderBoardVote>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DungeonLeaderBoardVote> _parser = new pb::MessageParser<DungeonLeaderBoardVote>(() => new DungeonLeaderBoardVote());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DungeonLeaderBoardVote> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruDungeonLeaderBoardVoteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonLeaderBoardVote() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonLeaderBoardVote(DungeonLeaderBoardVote other) : this() {
      leaderBoardId_ = other.leaderBoardId_;
      voteCounterId_ = other.voteCounterId_;
      canVote_ = other.canVote_;
      state_ = other.state_;
      blockedMemberIds_ = other.blockedMemberIds_.Clone();
      members_ = other.members_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DungeonLeaderBoardVote Clone() {
      return new DungeonLeaderBoardVote(this);
    }

    /// <summary>Field number for the "leaderBoardId" field.</summary>
    public const int LeaderBoardIdFieldNumber = 1;
    private int leaderBoardId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LeaderBoardId {
      get { return leaderBoardId_; }
      set {
        leaderBoardId_ = value;
      }
    }

    /// <summary>Field number for the "voteCounterId" field.</summary>
    public const int VoteCounterIdFieldNumber = 2;
    private int voteCounterId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int VoteCounterId {
      get { return voteCounterId_; }
      set {
        voteCounterId_ = value;
      }
    }

    /// <summary>Field number for the "canVote" field.</summary>
    public const int CanVoteFieldNumber = 3;
    private bool canVote_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanVote {
      get { return canVote_; }
      set {
        canVote_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 4;
    private int state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "blockedMemberIds" field.</summary>
    public const int BlockedMemberIdsFieldNumber = 5;
    private static readonly pb::FieldCodec<long> _repeated_blockedMemberIds_codec
        = pb::FieldCodec.ForInt64(42);
    private readonly pbc::RepeatedField<long> blockedMemberIds_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> BlockedMemberIds {
      get { return blockedMemberIds_; }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 6;
    private static readonly pbc::MapField<long, global::Zproto.DungeonLeaderBoardVoteMember>.Codec _map_members_codec
        = new pbc::MapField<long, global::Zproto.DungeonLeaderBoardVoteMember>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Zproto.DungeonLeaderBoardVoteMember.Parser), 50);
    private readonly pbc::MapField<long, global::Zproto.DungeonLeaderBoardVoteMember> members_ = new pbc::MapField<long, global::Zproto.DungeonLeaderBoardVoteMember>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Zproto.DungeonLeaderBoardVoteMember> Members {
      get { return members_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DungeonLeaderBoardVote);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DungeonLeaderBoardVote other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LeaderBoardId != other.LeaderBoardId) return false;
      if (VoteCounterId != other.VoteCounterId) return false;
      if (CanVote != other.CanVote) return false;
      if (State != other.State) return false;
      if(!blockedMemberIds_.Equals(other.blockedMemberIds_)) return false;
      if (!Members.Equals(other.Members)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LeaderBoardId != 0) hash ^= LeaderBoardId.GetHashCode();
      if (VoteCounterId != 0) hash ^= VoteCounterId.GetHashCode();
      if (CanVote != false) hash ^= CanVote.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      hash ^= blockedMemberIds_.GetHashCode();
      hash ^= Members.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LeaderBoardId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LeaderBoardId);
      }
      if (VoteCounterId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(VoteCounterId);
      }
      if (CanVote != false) {
        output.WriteRawTag(24);
        output.WriteBool(CanVote);
      }
      if (State != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(State);
      }
      blockedMemberIds_.WriteTo(output, _repeated_blockedMemberIds_codec);
      members_.WriteTo(output, _map_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LeaderBoardId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LeaderBoardId);
      }
      if (VoteCounterId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(VoteCounterId);
      }
      if (CanVote != false) {
        output.WriteRawTag(24);
        output.WriteBool(CanVote);
      }
      if (State != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(State);
      }
      blockedMemberIds_.WriteTo(ref output, _repeated_blockedMemberIds_codec);
      members_.WriteTo(ref output, _map_members_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LeaderBoardId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LeaderBoardId);
      }
      if (VoteCounterId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(VoteCounterId);
      }
      if (CanVote != false) {
        size += 1 + 1;
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      size += blockedMemberIds_.CalculateSize(_repeated_blockedMemberIds_codec);
      size += members_.CalculateSize(_map_members_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DungeonLeaderBoardVote other) {
      if (other == null) {
        return;
      }
      if (other.LeaderBoardId != 0) {
        LeaderBoardId = other.LeaderBoardId;
      }
      if (other.VoteCounterId != 0) {
        VoteCounterId = other.VoteCounterId;
      }
      if (other.CanVote != false) {
        CanVote = other.CanVote;
      }
      if (other.State != 0) {
        State = other.State;
      }
      blockedMemberIds_.Add(other.blockedMemberIds_);
      members_.MergeFrom(other.members_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LeaderBoardId = input.ReadInt32();
            break;
          }
          case 16: {
            VoteCounterId = input.ReadInt32();
            break;
          }
          case 24: {
            CanVote = input.ReadBool();
            break;
          }
          case 32: {
            State = input.ReadInt32();
            break;
          }
          case 42:
          case 40: {
            blockedMemberIds_.AddEntriesFrom(input, _repeated_blockedMemberIds_codec);
            break;
          }
          case 50: {
            members_.AddEntriesFrom(input, _map_members_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LeaderBoardId = input.ReadInt32();
            break;
          }
          case 16: {
            VoteCounterId = input.ReadInt32();
            break;
          }
          case 24: {
            CanVote = input.ReadBool();
            break;
          }
          case 32: {
            State = input.ReadInt32();
            break;
          }
          case 42:
          case 40: {
            blockedMemberIds_.AddEntriesFrom(ref input, _repeated_blockedMemberIds_codec);
            break;
          }
          case 50: {
            members_.AddEntriesFrom(ref input, _map_members_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
