// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_apply_join_team_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_apply_join_team_request.proto</summary>
  public static partial class StruApplyJoinTeamRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_apply_join_team_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruApplyJoinTeamRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJzdHJ1X2FwcGx5X2pvaW5fdGVhbV9yZXF1ZXN0LnByb3RvEgZ6cHJvdG8a",
            "IWVudW1fZV90ZWFtX2pvaW5fYXBwbHlfdHlwZS5wcm90byKUAQoUQXBwbHlK",
            "b2luVGVhbVJlcXVlc3QSIgoMdGFyZ2V0VGVhbUlkGAMgASgDUgx0YXJnZXRU",
            "ZWFtSWQSOAoJYXBwbHlUeXBlGAQgASgOMhouenByb3RvLkVUZWFtSm9pbkFw",
            "cGx5VHlwZVIJYXBwbHlUeXBlEh4KCnNlbGZUZWFtSWQYBSABKANSCnNlbGZU",
            "ZWFtSWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumETeamJoinApplyTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.ApplyJoinTeamRequest), global::Zproto.ApplyJoinTeamRequest.Parser, new[]{ "TargetTeamId", "ApplyType", "SelfTeamId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApplyJoinTeamRequest : pb::IMessage<ApplyJoinTeamRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApplyJoinTeamRequest> _parser = new pb::MessageParser<ApplyJoinTeamRequest>(() => new ApplyJoinTeamRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApplyJoinTeamRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruApplyJoinTeamRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplyJoinTeamRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplyJoinTeamRequest(ApplyJoinTeamRequest other) : this() {
      targetTeamId_ = other.targetTeamId_;
      applyType_ = other.applyType_;
      selfTeamId_ = other.selfTeamId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApplyJoinTeamRequest Clone() {
      return new ApplyJoinTeamRequest(this);
    }

    /// <summary>Field number for the "targetTeamId" field.</summary>
    public const int TargetTeamIdFieldNumber = 3;
    private long targetTeamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetTeamId {
      get { return targetTeamId_; }
      set {
        targetTeamId_ = value;
      }
    }

    /// <summary>Field number for the "applyType" field.</summary>
    public const int ApplyTypeFieldNumber = 4;
    private global::Zproto.ETeamJoinApplyType applyType_ = global::Zproto.ETeamJoinApplyType.Personal;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ETeamJoinApplyType ApplyType {
      get { return applyType_; }
      set {
        applyType_ = value;
      }
    }

    /// <summary>Field number for the "selfTeamId" field.</summary>
    public const int SelfTeamIdFieldNumber = 5;
    private long selfTeamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SelfTeamId {
      get { return selfTeamId_; }
      set {
        selfTeamId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApplyJoinTeamRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApplyJoinTeamRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TargetTeamId != other.TargetTeamId) return false;
      if (ApplyType != other.ApplyType) return false;
      if (SelfTeamId != other.SelfTeamId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TargetTeamId != 0L) hash ^= TargetTeamId.GetHashCode();
      if (ApplyType != global::Zproto.ETeamJoinApplyType.Personal) hash ^= ApplyType.GetHashCode();
      if (SelfTeamId != 0L) hash ^= SelfTeamId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TargetTeamId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetTeamId);
      }
      if (ApplyType != global::Zproto.ETeamJoinApplyType.Personal) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ApplyType);
      }
      if (SelfTeamId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(SelfTeamId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TargetTeamId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetTeamId);
      }
      if (ApplyType != global::Zproto.ETeamJoinApplyType.Personal) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ApplyType);
      }
      if (SelfTeamId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(SelfTeamId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TargetTeamId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetTeamId);
      }
      if (ApplyType != global::Zproto.ETeamJoinApplyType.Personal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ApplyType);
      }
      if (SelfTeamId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SelfTeamId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApplyJoinTeamRequest other) {
      if (other == null) {
        return;
      }
      if (other.TargetTeamId != 0L) {
        TargetTeamId = other.TargetTeamId;
      }
      if (other.ApplyType != global::Zproto.ETeamJoinApplyType.Personal) {
        ApplyType = other.ApplyType;
      }
      if (other.SelfTeamId != 0L) {
        SelfTeamId = other.SelfTeamId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            TargetTeamId = input.ReadInt64();
            break;
          }
          case 32: {
            ApplyType = (global::Zproto.ETeamJoinApplyType) input.ReadEnum();
            break;
          }
          case 40: {
            SelfTeamId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            TargetTeamId = input.ReadInt64();
            break;
          }
          case 32: {
            ApplyType = (global::Zproto.ETeamJoinApplyType) input.ReadEnum();
            break;
          }
          case 40: {
            SelfTeamId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
