// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_leader_board_record.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_leader_board_record.proto</summary>
  public static partial class StruLeaderBoardRecordReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_leader_board_record.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruLeaderBoardRecordReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zdHJ1X2xlYWRlcl9ib2FyZF9yZWNvcmQucHJvdG8SBnpwcm90bxoic3Ry",
            "dV9sZWFkZXJfYm9hcmRfc3ViX3JlY29yZC5wcm90bxofc3RydV9wbGF5ZXJf",
            "cmFua19tZXRhZGF0YS5wcm90byKXAgoRTGVhZGVyQm9hcmRSZWNvcmQSEgoE",
            "cmFuaxgBIAEoBVIEcmFuaxIaCghyYW5rRGF0YRgCIAMoA1IIcmFua0RhdGES",
            "NAoHbWVtYmVycxgDIAMoCzIaLnpwcm90by5QbGF5ZXJSYW5rTWV0YWRhdGFS",
            "B21lbWJlcnMSHAoJc2hvd1BhcmFtGAQgAygJUglzaG93UGFyYW0SPAoKc3Vi",
            "UmVjb3JkcxgFIAMoCzIcLnpwcm90by5MZWFkZXJCb2FyZFN1YlJlY29yZFIK",
            "c3ViUmVjb3JkcxIcCglzdWJqZWN0SWQYBiABKAlSCXN1YmplY3RJZBIiCgxh",
            "dWRpdGluZ0xpc3QYByADKAVSDGF1ZGl0aW5nTGlzdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruLeaderBoardSubRecordReflection.Descriptor, global::Zproto.StruPlayerRankMetadataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.LeaderBoardRecord), global::Zproto.LeaderBoardRecord.Parser, new[]{ "Rank", "RankData", "Members", "ShowParam", "SubRecords", "SubjectId", "AuditingList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LeaderBoardRecord : pb::IMessage<LeaderBoardRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LeaderBoardRecord> _parser = new pb::MessageParser<LeaderBoardRecord>(() => new LeaderBoardRecord());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LeaderBoardRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruLeaderBoardRecordReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardRecord(LeaderBoardRecord other) : this() {
      rank_ = other.rank_;
      rankData_ = other.rankData_.Clone();
      members_ = other.members_.Clone();
      showParam_ = other.showParam_.Clone();
      subRecords_ = other.subRecords_.Clone();
      subjectId_ = other.subjectId_;
      auditingList_ = other.auditingList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardRecord Clone() {
      return new LeaderBoardRecord(this);
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 1;
    private int rank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    /// <summary>Field number for the "rankData" field.</summary>
    public const int RankDataFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_rankData_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> rankData_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> RankData {
      get { return rankData_; }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Zproto.PlayerRankMetadata> _repeated_members_codec
        = pb::FieldCodec.ForMessage(26, global::Zproto.PlayerRankMetadata.Parser);
    private readonly pbc::RepeatedField<global::Zproto.PlayerRankMetadata> members_ = new pbc::RepeatedField<global::Zproto.PlayerRankMetadata>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zproto.PlayerRankMetadata> Members {
      get { return members_; }
    }

    /// <summary>Field number for the "showParam" field.</summary>
    public const int ShowParamFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_showParam_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> showParam_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ShowParam {
      get { return showParam_; }
    }

    /// <summary>Field number for the "subRecords" field.</summary>
    public const int SubRecordsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Zproto.LeaderBoardSubRecord> _repeated_subRecords_codec
        = pb::FieldCodec.ForMessage(42, global::Zproto.LeaderBoardSubRecord.Parser);
    private readonly pbc::RepeatedField<global::Zproto.LeaderBoardSubRecord> subRecords_ = new pbc::RepeatedField<global::Zproto.LeaderBoardSubRecord>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zproto.LeaderBoardSubRecord> SubRecords {
      get { return subRecords_; }
    }

    /// <summary>Field number for the "subjectId" field.</summary>
    public const int SubjectIdFieldNumber = 6;
    private string subjectId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubjectId {
      get { return subjectId_; }
      set {
        subjectId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "auditingList" field.</summary>
    public const int AuditingListFieldNumber = 7;
    private static readonly pb::FieldCodec<int> _repeated_auditingList_codec
        = pb::FieldCodec.ForInt32(58);
    private readonly pbc::RepeatedField<int> auditingList_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AuditingList {
      get { return auditingList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LeaderBoardRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LeaderBoardRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Rank != other.Rank) return false;
      if(!rankData_.Equals(other.rankData_)) return false;
      if(!members_.Equals(other.members_)) return false;
      if(!showParam_.Equals(other.showParam_)) return false;
      if(!subRecords_.Equals(other.subRecords_)) return false;
      if (SubjectId != other.SubjectId) return false;
      if(!auditingList_.Equals(other.auditingList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Rank != 0) hash ^= Rank.GetHashCode();
      hash ^= rankData_.GetHashCode();
      hash ^= members_.GetHashCode();
      hash ^= showParam_.GetHashCode();
      hash ^= subRecords_.GetHashCode();
      if (SubjectId.Length != 0) hash ^= SubjectId.GetHashCode();
      hash ^= auditingList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Rank != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Rank);
      }
      rankData_.WriteTo(output, _repeated_rankData_codec);
      members_.WriteTo(output, _repeated_members_codec);
      showParam_.WriteTo(output, _repeated_showParam_codec);
      subRecords_.WriteTo(output, _repeated_subRecords_codec);
      if (SubjectId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SubjectId);
      }
      auditingList_.WriteTo(output, _repeated_auditingList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Rank != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Rank);
      }
      rankData_.WriteTo(ref output, _repeated_rankData_codec);
      members_.WriteTo(ref output, _repeated_members_codec);
      showParam_.WriteTo(ref output, _repeated_showParam_codec);
      subRecords_.WriteTo(ref output, _repeated_subRecords_codec);
      if (SubjectId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(SubjectId);
      }
      auditingList_.WriteTo(ref output, _repeated_auditingList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Rank != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rank);
      }
      size += rankData_.CalculateSize(_repeated_rankData_codec);
      size += members_.CalculateSize(_repeated_members_codec);
      size += showParam_.CalculateSize(_repeated_showParam_codec);
      size += subRecords_.CalculateSize(_repeated_subRecords_codec);
      if (SubjectId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubjectId);
      }
      size += auditingList_.CalculateSize(_repeated_auditingList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LeaderBoardRecord other) {
      if (other == null) {
        return;
      }
      if (other.Rank != 0) {
        Rank = other.Rank;
      }
      rankData_.Add(other.rankData_);
      members_.Add(other.members_);
      showParam_.Add(other.showParam_);
      subRecords_.Add(other.subRecords_);
      if (other.SubjectId.Length != 0) {
        SubjectId = other.SubjectId;
      }
      auditingList_.Add(other.auditingList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Rank = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            rankData_.AddEntriesFrom(input, _repeated_rankData_codec);
            break;
          }
          case 26: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
          case 34: {
            showParam_.AddEntriesFrom(input, _repeated_showParam_codec);
            break;
          }
          case 42: {
            subRecords_.AddEntriesFrom(input, _repeated_subRecords_codec);
            break;
          }
          case 50: {
            SubjectId = input.ReadString();
            break;
          }
          case 58:
          case 56: {
            auditingList_.AddEntriesFrom(input, _repeated_auditingList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Rank = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            rankData_.AddEntriesFrom(ref input, _repeated_rankData_codec);
            break;
          }
          case 26: {
            members_.AddEntriesFrom(ref input, _repeated_members_codec);
            break;
          }
          case 34: {
            showParam_.AddEntriesFrom(ref input, _repeated_showParam_codec);
            break;
          }
          case 42: {
            subRecords_.AddEntriesFrom(ref input, _repeated_subRecords_codec);
            break;
          }
          case 50: {
            SubjectId = input.ReadString();
            break;
          }
          case 58:
          case 56: {
            auditingList_.AddEntriesFrom(ref input, _repeated_auditingList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
