// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_team_list_show_member.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_team_list_show_member.proto</summary>
  public static partial class StruTeamListShowMemberReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_team_list_show_member.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruTeamListShowMemberReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBzdHJ1X3RlYW1fbGlzdF9zaG93X21lbWJlci5wcm90bxIGenByb3RvGhZz",
            "dHJ1X2F2YXRhcl9pbmZvLnByb3RvGhZlbnVtX2VfYm9keV9zaXplLnByb3Rv",
            "IqcCChJUZWFtTGlzdFNob3dNZW1iZXISFgoGY2hhcklkGAEgASgDUgZjaGFy",
            "SWQSEgoEbmFtZRgCIAEoCVIEbmFtZRIUCgVsZXZlbBgDIAEoBVIFbGV2ZWwS",
            "FgoGdGFsZW50GAQgASgFUgZ0YWxlbnQSGAoHc2NlbmVJZBgFIAEoBVIHc2Nl",
            "bmVJZBIyCgphdmF0YXJJbmZvGAYgASgLMhIuenByb3RvLkF2YXRhckluZm9S",
            "CmF2YXRhckluZm8SFgoGZ2VuZGVyGAcgASgFUgZnZW5kZXISLQoIYm9keVNp",
            "emUYCCABKA4yES56cHJvdG8uRUJvZHlTaXplUghib2R5U2l6ZRIiCgxwcm9m",
            "ZXNzaW9uSWQYCSABKAVSDHByb2Zlc3Npb25JZGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruAvatarInfoReflection.Descriptor, global::Zproto.EnumEBodySizeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.TeamListShowMember), global::Zproto.TeamListShowMember.Parser, new[]{ "CharId", "Name", "Level", "Talent", "SceneId", "AvatarInfo", "Gender", "BodySize", "ProfessionId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TeamListShowMember : pb::IMessage<TeamListShowMember>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeamListShowMember> _parser = new pb::MessageParser<TeamListShowMember>(() => new TeamListShowMember());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeamListShowMember> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruTeamListShowMemberReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamListShowMember() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamListShowMember(TeamListShowMember other) : this() {
      charId_ = other.charId_;
      name_ = other.name_;
      level_ = other.level_;
      talent_ = other.talent_;
      sceneId_ = other.sceneId_;
      avatarInfo_ = other.avatarInfo_ != null ? other.avatarInfo_.Clone() : null;
      gender_ = other.gender_;
      bodySize_ = other.bodySize_;
      professionId_ = other.professionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamListShowMember Clone() {
      return new TeamListShowMember(this);
    }

    /// <summary>Field number for the "charId" field.</summary>
    public const int CharIdFieldNumber = 1;
    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { return charId_; }
      set {
        charId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 3;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "talent" field.</summary>
    public const int TalentFieldNumber = 4;
    private int talent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Talent {
      get { return talent_; }
      set {
        talent_ = value;
      }
    }

    /// <summary>Field number for the "sceneId" field.</summary>
    public const int SceneIdFieldNumber = 5;
    private int sceneId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneId {
      get { return sceneId_; }
      set {
        sceneId_ = value;
      }
    }

    /// <summary>Field number for the "avatarInfo" field.</summary>
    public const int AvatarInfoFieldNumber = 6;
    private global::Zproto.AvatarInfo avatarInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.AvatarInfo AvatarInfo {
      get { return avatarInfo_; }
      set {
        avatarInfo_ = value;
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 7;
    private int gender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "bodySize" field.</summary>
    public const int BodySizeFieldNumber = 8;
    private global::Zproto.EBodySize bodySize_ = global::Zproto.EBodySize.BodySizeNull;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EBodySize BodySize {
      get { return bodySize_; }
      set {
        bodySize_ = value;
      }
    }

    /// <summary>Field number for the "professionId" field.</summary>
    public const int ProfessionIdFieldNumber = 9;
    private int professionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProfessionId {
      get { return professionId_; }
      set {
        professionId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeamListShowMember);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeamListShowMember other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharId != other.CharId) return false;
      if (Name != other.Name) return false;
      if (Level != other.Level) return false;
      if (Talent != other.Talent) return false;
      if (SceneId != other.SceneId) return false;
      if (!object.Equals(AvatarInfo, other.AvatarInfo)) return false;
      if (Gender != other.Gender) return false;
      if (BodySize != other.BodySize) return false;
      if (ProfessionId != other.ProfessionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharId != 0L) hash ^= CharId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Talent != 0) hash ^= Talent.GetHashCode();
      if (SceneId != 0) hash ^= SceneId.GetHashCode();
      if (avatarInfo_ != null) hash ^= AvatarInfo.GetHashCode();
      if (Gender != 0) hash ^= Gender.GetHashCode();
      if (BodySize != global::Zproto.EBodySize.BodySizeNull) hash ^= BodySize.GetHashCode();
      if (ProfessionId != 0) hash ^= ProfessionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Level != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Level);
      }
      if (Talent != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Talent);
      }
      if (SceneId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SceneId);
      }
      if (avatarInfo_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(AvatarInfo);
      }
      if (Gender != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Gender);
      }
      if (BodySize != global::Zproto.EBodySize.BodySizeNull) {
        output.WriteRawTag(64);
        output.WriteEnum((int) BodySize);
      }
      if (ProfessionId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(ProfessionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Level != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Level);
      }
      if (Talent != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Talent);
      }
      if (SceneId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(SceneId);
      }
      if (avatarInfo_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(AvatarInfo);
      }
      if (Gender != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Gender);
      }
      if (BodySize != global::Zproto.EBodySize.BodySizeNull) {
        output.WriteRawTag(64);
        output.WriteEnum((int) BodySize);
      }
      if (ProfessionId != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(ProfessionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Talent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Talent);
      }
      if (SceneId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneId);
      }
      if (avatarInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AvatarInfo);
      }
      if (Gender != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gender);
      }
      if (BodySize != global::Zproto.EBodySize.BodySizeNull) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BodySize);
      }
      if (ProfessionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProfessionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeamListShowMember other) {
      if (other == null) {
        return;
      }
      if (other.CharId != 0L) {
        CharId = other.CharId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Talent != 0) {
        Talent = other.Talent;
      }
      if (other.SceneId != 0) {
        SceneId = other.SceneId;
      }
      if (other.avatarInfo_ != null) {
        if (avatarInfo_ == null) {
          AvatarInfo = new global::Zproto.AvatarInfo();
        }
        AvatarInfo.MergeFrom(other.AvatarInfo);
      }
      if (other.Gender != 0) {
        Gender = other.Gender;
      }
      if (other.BodySize != global::Zproto.EBodySize.BodySizeNull) {
        BodySize = other.BodySize;
      }
      if (other.ProfessionId != 0) {
        ProfessionId = other.ProfessionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Level = input.ReadInt32();
            break;
          }
          case 32: {
            Talent = input.ReadInt32();
            break;
          }
          case 40: {
            SceneId = input.ReadInt32();
            break;
          }
          case 50: {
            if (avatarInfo_ == null) {
              AvatarInfo = new global::Zproto.AvatarInfo();
            }
            input.ReadMessage(AvatarInfo);
            break;
          }
          case 56: {
            Gender = input.ReadInt32();
            break;
          }
          case 64: {
            BodySize = (global::Zproto.EBodySize) input.ReadEnum();
            break;
          }
          case 72: {
            ProfessionId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Level = input.ReadInt32();
            break;
          }
          case 32: {
            Talent = input.ReadInt32();
            break;
          }
          case 40: {
            SceneId = input.ReadInt32();
            break;
          }
          case 50: {
            if (avatarInfo_ == null) {
              AvatarInfo = new global::Zproto.AvatarInfo();
            }
            input.ReadMessage(AvatarInfo);
            break;
          }
          case 56: {
            Gender = input.ReadInt32();
            break;
          }
          case 64: {
            BodySize = (global::Zproto.EBodySize) input.ReadEnum();
            break;
          }
          case 72: {
            ProfessionId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
