// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_team_list_show_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_team_list_show_info.proto</summary>
  public static partial class StruTeamListShowInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_team_list_show_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruTeamListShowInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zdHJ1X3RlYW1fbGlzdF9zaG93X2luZm8ucHJvdG8SBnpwcm90bxodZW51",
            "bV9lX3RlYW1fbWVtYmVyX3R5cGUucHJvdG8aIHN0cnVfdGVhbV9saXN0X3No",
            "b3dfbWVtYmVyLnByb3RvIpUEChBUZWFtTGlzdFNob3dJbmZvEhYKBnRlYW1J",
            "ZBgBIAEoA1IGdGVhbUlkEhoKCGxlYWRlcklkGAIgASgDUghsZWFkZXJJZBIa",
            "Cgh0YXJnZXRJZBgDIAEoBVIIdGFyZ2V0SWQSPwoOdGVhbU1lbWJlclR5cGUY",
            "BCABKA4yFy56cHJvdG8uRVRlYW1NZW1iZXJUeXBlUg50ZWFtTWVtYmVyVHlw",
            "ZRISCgRkZXNjGAUgASgJUgRkZXNjElEKDWpvaW5Db25kaXRpb24YBiADKAsy",
            "Ky56cHJvdG8uVGVhbUxpc3RTaG93SW5mby5Kb2luQ29uZGl0aW9uRW50cnlS",
            "DWpvaW5Db25kaXRpb24SYAoSdGVhbUxpc3RTaG93TWVtYmVyGAcgAygLMjAu",
            "enByb3RvLlRlYW1MaXN0U2hvd0luZm8uVGVhbUxpc3RTaG93TWVtYmVyRW50",
            "cnlSEnRlYW1MaXN0U2hvd01lbWJlchIaCghtYXRjaGluZxgIIAEoCFIIbWF0",
            "Y2hpbmcaNAoSSm9pbkNvbmRpdGlvbkVudHJ5EgsKA2tleRgBIAEoBRINCgV2",
            "YWx1ZRgCIAEoAzoCOAEaVQoXVGVhbUxpc3RTaG93TWVtYmVyRW50cnkSCwoD",
            "a2V5GAEgASgDEikKBXZhbHVlGAIgASgLMhouenByb3RvLlRlYW1MaXN0U2hv",
            "d01lbWJlcjoCOAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumETeamMemberTypeReflection.Descriptor, global::Zproto.StruTeamListShowMemberReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.TeamListShowInfo), global::Zproto.TeamListShowInfo.Parser, new[]{ "TeamId", "LeaderId", "TargetId", "TeamMemberType", "Desc", "JoinCondition", "TeamListShowMember", "Matching" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TeamListShowInfo : pb::IMessage<TeamListShowInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeamListShowInfo> _parser = new pb::MessageParser<TeamListShowInfo>(() => new TeamListShowInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeamListShowInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruTeamListShowInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamListShowInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamListShowInfo(TeamListShowInfo other) : this() {
      teamId_ = other.teamId_;
      leaderId_ = other.leaderId_;
      targetId_ = other.targetId_;
      teamMemberType_ = other.teamMemberType_;
      desc_ = other.desc_;
      joinCondition_ = other.joinCondition_.Clone();
      teamListShowMember_ = other.teamListShowMember_.Clone();
      matching_ = other.matching_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamListShowInfo Clone() {
      return new TeamListShowInfo(this);
    }

    /// <summary>Field number for the "teamId" field.</summary>
    public const int TeamIdFieldNumber = 1;
    private long teamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TeamId {
      get { return teamId_; }
      set {
        teamId_ = value;
      }
    }

    /// <summary>Field number for the "leaderId" field.</summary>
    public const int LeaderIdFieldNumber = 2;
    private long leaderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LeaderId {
      get { return leaderId_; }
      set {
        leaderId_ = value;
      }
    }

    /// <summary>Field number for the "targetId" field.</summary>
    public const int TargetIdFieldNumber = 3;
    private int targetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "teamMemberType" field.</summary>
    public const int TeamMemberTypeFieldNumber = 4;
    private global::Zproto.ETeamMemberType teamMemberType_ = global::Zproto.ETeamMemberType.Five;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ETeamMemberType TeamMemberType {
      get { return teamMemberType_; }
      set {
        teamMemberType_ = value;
      }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 5;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "joinCondition" field.</summary>
    public const int JoinConditionFieldNumber = 6;
    private static readonly pbc::MapField<int, long>.Codec _map_joinCondition_codec
        = new pbc::MapField<int, long>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt64(16, 0L), 50);
    private readonly pbc::MapField<int, long> joinCondition_ = new pbc::MapField<int, long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, long> JoinCondition {
      get { return joinCondition_; }
    }

    /// <summary>Field number for the "teamListShowMember" field.</summary>
    public const int TeamListShowMemberFieldNumber = 7;
    private static readonly pbc::MapField<long, global::Zproto.TeamListShowMember>.Codec _map_teamListShowMember_codec
        = new pbc::MapField<long, global::Zproto.TeamListShowMember>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Zproto.TeamListShowMember.Parser), 58);
    private readonly pbc::MapField<long, global::Zproto.TeamListShowMember> teamListShowMember_ = new pbc::MapField<long, global::Zproto.TeamListShowMember>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Zproto.TeamListShowMember> TeamListShowMember {
      get { return teamListShowMember_; }
    }

    /// <summary>Field number for the "matching" field.</summary>
    public const int MatchingFieldNumber = 8;
    private bool matching_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Matching {
      get { return matching_; }
      set {
        matching_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeamListShowInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeamListShowInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TeamId != other.TeamId) return false;
      if (LeaderId != other.LeaderId) return false;
      if (TargetId != other.TargetId) return false;
      if (TeamMemberType != other.TeamMemberType) return false;
      if (Desc != other.Desc) return false;
      if (!JoinCondition.Equals(other.JoinCondition)) return false;
      if (!TeamListShowMember.Equals(other.TeamListShowMember)) return false;
      if (Matching != other.Matching) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TeamId != 0L) hash ^= TeamId.GetHashCode();
      if (LeaderId != 0L) hash ^= LeaderId.GetHashCode();
      if (TargetId != 0) hash ^= TargetId.GetHashCode();
      if (TeamMemberType != global::Zproto.ETeamMemberType.Five) hash ^= TeamMemberType.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      hash ^= JoinCondition.GetHashCode();
      hash ^= TeamListShowMember.GetHashCode();
      if (Matching != false) hash ^= Matching.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TeamId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TeamId);
      }
      if (LeaderId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LeaderId);
      }
      if (TargetId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TargetId);
      }
      if (TeamMemberType != global::Zproto.ETeamMemberType.Five) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TeamMemberType);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Desc);
      }
      joinCondition_.WriteTo(output, _map_joinCondition_codec);
      teamListShowMember_.WriteTo(output, _map_teamListShowMember_codec);
      if (Matching != false) {
        output.WriteRawTag(64);
        output.WriteBool(Matching);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TeamId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TeamId);
      }
      if (LeaderId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LeaderId);
      }
      if (TargetId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TargetId);
      }
      if (TeamMemberType != global::Zproto.ETeamMemberType.Five) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TeamMemberType);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Desc);
      }
      joinCondition_.WriteTo(ref output, _map_joinCondition_codec);
      teamListShowMember_.WriteTo(ref output, _map_teamListShowMember_codec);
      if (Matching != false) {
        output.WriteRawTag(64);
        output.WriteBool(Matching);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TeamId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TeamId);
      }
      if (LeaderId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LeaderId);
      }
      if (TargetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetId);
      }
      if (TeamMemberType != global::Zproto.ETeamMemberType.Five) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TeamMemberType);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      size += joinCondition_.CalculateSize(_map_joinCondition_codec);
      size += teamListShowMember_.CalculateSize(_map_teamListShowMember_codec);
      if (Matching != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeamListShowInfo other) {
      if (other == null) {
        return;
      }
      if (other.TeamId != 0L) {
        TeamId = other.TeamId;
      }
      if (other.LeaderId != 0L) {
        LeaderId = other.LeaderId;
      }
      if (other.TargetId != 0) {
        TargetId = other.TargetId;
      }
      if (other.TeamMemberType != global::Zproto.ETeamMemberType.Five) {
        TeamMemberType = other.TeamMemberType;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      joinCondition_.MergeFrom(other.joinCondition_);
      teamListShowMember_.MergeFrom(other.teamListShowMember_);
      if (other.Matching != false) {
        Matching = other.Matching;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TeamId = input.ReadInt64();
            break;
          }
          case 16: {
            LeaderId = input.ReadInt64();
            break;
          }
          case 24: {
            TargetId = input.ReadInt32();
            break;
          }
          case 32: {
            TeamMemberType = (global::Zproto.ETeamMemberType) input.ReadEnum();
            break;
          }
          case 42: {
            Desc = input.ReadString();
            break;
          }
          case 50: {
            joinCondition_.AddEntriesFrom(input, _map_joinCondition_codec);
            break;
          }
          case 58: {
            teamListShowMember_.AddEntriesFrom(input, _map_teamListShowMember_codec);
            break;
          }
          case 64: {
            Matching = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TeamId = input.ReadInt64();
            break;
          }
          case 16: {
            LeaderId = input.ReadInt64();
            break;
          }
          case 24: {
            TargetId = input.ReadInt32();
            break;
          }
          case 32: {
            TeamMemberType = (global::Zproto.ETeamMemberType) input.ReadEnum();
            break;
          }
          case 42: {
            Desc = input.ReadString();
            break;
          }
          case 50: {
            joinCondition_.AddEntriesFrom(ref input, _map_joinCondition_codec);
            break;
          }
          case 58: {
            teamListShowMember_.AddEntriesFrom(ref input, _map_teamListShowMember_codec);
            break;
          }
          case 64: {
            Matching = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
