// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_report_leader_board.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_report_leader_board.proto</summary>
  public static partial class StruReportLeaderBoardReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_report_leader_board.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruReportLeaderBoardReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zdHJ1X3JlcG9ydF9sZWFkZXJfYm9hcmQucHJvdG8SBnpwcm90byKXAQoR",
            "UmVwb3J0TGVhZGVyQm9hcmQSJAoNbGVhZGVyQm9hcmRJZBgBIAEoBVINbGVh",
            "ZGVyQm9hcmRJZBIcCglzdWJqZWN0SWQYAiABKAlSCXN1YmplY3RJZBIiCgx0",
            "YXJnZXRDaGFySWQYAyABKANSDHRhcmdldENoYXJJZBIaCghjeWNsZUtleRgE",
            "IAEoA1IIY3ljbGVLZXliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.ReportLeaderBoard), global::Zproto.ReportLeaderBoard.Parser, new[]{ "LeaderBoardId", "SubjectId", "TargetCharId", "CycleKey" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ReportLeaderBoard : pb::IMessage<ReportLeaderBoard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReportLeaderBoard> _parser = new pb::MessageParser<ReportLeaderBoard>(() => new ReportLeaderBoard());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReportLeaderBoard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruReportLeaderBoardReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReportLeaderBoard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReportLeaderBoard(ReportLeaderBoard other) : this() {
      leaderBoardId_ = other.leaderBoardId_;
      subjectId_ = other.subjectId_;
      targetCharId_ = other.targetCharId_;
      cycleKey_ = other.cycleKey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReportLeaderBoard Clone() {
      return new ReportLeaderBoard(this);
    }

    /// <summary>Field number for the "leaderBoardId" field.</summary>
    public const int LeaderBoardIdFieldNumber = 1;
    private int leaderBoardId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LeaderBoardId {
      get { return leaderBoardId_; }
      set {
        leaderBoardId_ = value;
      }
    }

    /// <summary>Field number for the "subjectId" field.</summary>
    public const int SubjectIdFieldNumber = 2;
    private string subjectId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubjectId {
      get { return subjectId_; }
      set {
        subjectId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "targetCharId" field.</summary>
    public const int TargetCharIdFieldNumber = 3;
    private long targetCharId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetCharId {
      get { return targetCharId_; }
      set {
        targetCharId_ = value;
      }
    }

    /// <summary>Field number for the "cycleKey" field.</summary>
    public const int CycleKeyFieldNumber = 4;
    private long cycleKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CycleKey {
      get { return cycleKey_; }
      set {
        cycleKey_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReportLeaderBoard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReportLeaderBoard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LeaderBoardId != other.LeaderBoardId) return false;
      if (SubjectId != other.SubjectId) return false;
      if (TargetCharId != other.TargetCharId) return false;
      if (CycleKey != other.CycleKey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LeaderBoardId != 0) hash ^= LeaderBoardId.GetHashCode();
      if (SubjectId.Length != 0) hash ^= SubjectId.GetHashCode();
      if (TargetCharId != 0L) hash ^= TargetCharId.GetHashCode();
      if (CycleKey != 0L) hash ^= CycleKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LeaderBoardId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LeaderBoardId);
      }
      if (SubjectId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SubjectId);
      }
      if (TargetCharId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetCharId);
      }
      if (CycleKey != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(CycleKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LeaderBoardId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LeaderBoardId);
      }
      if (SubjectId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SubjectId);
      }
      if (TargetCharId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetCharId);
      }
      if (CycleKey != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(CycleKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LeaderBoardId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LeaderBoardId);
      }
      if (SubjectId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubjectId);
      }
      if (TargetCharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetCharId);
      }
      if (CycleKey != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CycleKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReportLeaderBoard other) {
      if (other == null) {
        return;
      }
      if (other.LeaderBoardId != 0) {
        LeaderBoardId = other.LeaderBoardId;
      }
      if (other.SubjectId.Length != 0) {
        SubjectId = other.SubjectId;
      }
      if (other.TargetCharId != 0L) {
        TargetCharId = other.TargetCharId;
      }
      if (other.CycleKey != 0L) {
        CycleKey = other.CycleKey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LeaderBoardId = input.ReadInt32();
            break;
          }
          case 18: {
            SubjectId = input.ReadString();
            break;
          }
          case 24: {
            TargetCharId = input.ReadInt64();
            break;
          }
          case 32: {
            CycleKey = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LeaderBoardId = input.ReadInt32();
            break;
          }
          case 18: {
            SubjectId = input.ReadString();
            break;
          }
          case 24: {
            TargetCharId = input.ReadInt64();
            break;
          }
          case 32: {
            CycleKey = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
