// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_team_dungeon_key_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_team_dungeon_key_info.proto</summary>
  public static partial class StruTeamDungeonKeyInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_team_dungeon_key_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruTeamDungeonKeyInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBzdHJ1X3RlYW1fZHVuZ2Vvbl9rZXlfaW5mby5wcm90bxIGenByb3RvGi5z",
            "dHJ1X3RlYW1fZHVuZ2Vvbl9sZWFkZXJfYm9hcmRfdm90ZV9pbmZvLnByb3Rv",
            "IvABChJUZWFtRHVuZ2VvbktleUluZm8SFgoGY2hhcklkGAEgASgDUgZjaGFy",
            "SWQSJgoOcm9sbEF3YXJkQ291bnQYAiABKAVSDnJvbGxBd2FyZENvdW50EiQK",
            "DWtleUF3YXJkQ291bnQYAyABKAVSDWtleUF3YXJkQ291bnQSGgoIaXNBc3Np",
            "c3QYBCABKAhSCGlzQXNzaXN0ElgKE2xlYWRlckJvYXJkVm90ZUluZm8YBSAB",
            "KAsyJi56cHJvdG8uVGVhbUR1bmdlb25MZWFkZXJCb2FyZFZvdGVJbmZvUhNs",
            "ZWFkZXJCb2FyZFZvdGVJbmZvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruTeamDungeonLeaderBoardVoteInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.TeamDungeonKeyInfo), global::Zproto.TeamDungeonKeyInfo.Parser, new[]{ "CharId", "RollAwardCount", "KeyAwardCount", "IsAssist", "LeaderBoardVoteInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TeamDungeonKeyInfo : pb::IMessage<TeamDungeonKeyInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeamDungeonKeyInfo> _parser = new pb::MessageParser<TeamDungeonKeyInfo>(() => new TeamDungeonKeyInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeamDungeonKeyInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruTeamDungeonKeyInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamDungeonKeyInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamDungeonKeyInfo(TeamDungeonKeyInfo other) : this() {
      charId_ = other.charId_;
      rollAwardCount_ = other.rollAwardCount_;
      keyAwardCount_ = other.keyAwardCount_;
      isAssist_ = other.isAssist_;
      leaderBoardVoteInfo_ = other.leaderBoardVoteInfo_ != null ? other.leaderBoardVoteInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamDungeonKeyInfo Clone() {
      return new TeamDungeonKeyInfo(this);
    }

    /// <summary>Field number for the "charId" field.</summary>
    public const int CharIdFieldNumber = 1;
    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { return charId_; }
      set {
        charId_ = value;
      }
    }

    /// <summary>Field number for the "rollAwardCount" field.</summary>
    public const int RollAwardCountFieldNumber = 2;
    private int rollAwardCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RollAwardCount {
      get { return rollAwardCount_; }
      set {
        rollAwardCount_ = value;
      }
    }

    /// <summary>Field number for the "keyAwardCount" field.</summary>
    public const int KeyAwardCountFieldNumber = 3;
    private int keyAwardCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int KeyAwardCount {
      get { return keyAwardCount_; }
      set {
        keyAwardCount_ = value;
      }
    }

    /// <summary>Field number for the "isAssist" field.</summary>
    public const int IsAssistFieldNumber = 4;
    private bool isAssist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAssist {
      get { return isAssist_; }
      set {
        isAssist_ = value;
      }
    }

    /// <summary>Field number for the "leaderBoardVoteInfo" field.</summary>
    public const int LeaderBoardVoteInfoFieldNumber = 5;
    private global::Zproto.TeamDungeonLeaderBoardVoteInfo leaderBoardVoteInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.TeamDungeonLeaderBoardVoteInfo LeaderBoardVoteInfo {
      get { return leaderBoardVoteInfo_; }
      set {
        leaderBoardVoteInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeamDungeonKeyInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeamDungeonKeyInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharId != other.CharId) return false;
      if (RollAwardCount != other.RollAwardCount) return false;
      if (KeyAwardCount != other.KeyAwardCount) return false;
      if (IsAssist != other.IsAssist) return false;
      if (!object.Equals(LeaderBoardVoteInfo, other.LeaderBoardVoteInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharId != 0L) hash ^= CharId.GetHashCode();
      if (RollAwardCount != 0) hash ^= RollAwardCount.GetHashCode();
      if (KeyAwardCount != 0) hash ^= KeyAwardCount.GetHashCode();
      if (IsAssist != false) hash ^= IsAssist.GetHashCode();
      if (leaderBoardVoteInfo_ != null) hash ^= LeaderBoardVoteInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (RollAwardCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RollAwardCount);
      }
      if (KeyAwardCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(KeyAwardCount);
      }
      if (IsAssist != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsAssist);
      }
      if (leaderBoardVoteInfo_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LeaderBoardVoteInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (RollAwardCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RollAwardCount);
      }
      if (KeyAwardCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(KeyAwardCount);
      }
      if (IsAssist != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsAssist);
      }
      if (leaderBoardVoteInfo_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(LeaderBoardVoteInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (RollAwardCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RollAwardCount);
      }
      if (KeyAwardCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(KeyAwardCount);
      }
      if (IsAssist != false) {
        size += 1 + 1;
      }
      if (leaderBoardVoteInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaderBoardVoteInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeamDungeonKeyInfo other) {
      if (other == null) {
        return;
      }
      if (other.CharId != 0L) {
        CharId = other.CharId;
      }
      if (other.RollAwardCount != 0) {
        RollAwardCount = other.RollAwardCount;
      }
      if (other.KeyAwardCount != 0) {
        KeyAwardCount = other.KeyAwardCount;
      }
      if (other.IsAssist != false) {
        IsAssist = other.IsAssist;
      }
      if (other.leaderBoardVoteInfo_ != null) {
        if (leaderBoardVoteInfo_ == null) {
          LeaderBoardVoteInfo = new global::Zproto.TeamDungeonLeaderBoardVoteInfo();
        }
        LeaderBoardVoteInfo.MergeFrom(other.LeaderBoardVoteInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 16: {
            RollAwardCount = input.ReadInt32();
            break;
          }
          case 24: {
            KeyAwardCount = input.ReadInt32();
            break;
          }
          case 32: {
            IsAssist = input.ReadBool();
            break;
          }
          case 42: {
            if (leaderBoardVoteInfo_ == null) {
              LeaderBoardVoteInfo = new global::Zproto.TeamDungeonLeaderBoardVoteInfo();
            }
            input.ReadMessage(LeaderBoardVoteInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 16: {
            RollAwardCount = input.ReadInt32();
            break;
          }
          case 24: {
            KeyAwardCount = input.ReadInt32();
            break;
          }
          case 32: {
            IsAssist = input.ReadBool();
            break;
          }
          case 42: {
            if (leaderBoardVoteInfo_ == null) {
              LeaderBoardVoteInfo = new global::Zproto.TeamDungeonLeaderBoardVoteInfo();
            }
            input.ReadMessage(LeaderBoardVoteInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
