// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_team_join_apply_list_item.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_team_join_apply_list_item.proto</summary>
  public static partial class StruTeamJoinApplyListItemReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_team_join_apply_list_item.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruTeamJoinApplyListItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRzdHJ1X3RlYW1fam9pbl9hcHBseV9saXN0X2l0ZW0ucHJvdG8SBnpwcm90",
            "bxohZW51bV9lX3RlYW1fam9pbl9hcHBseV90eXBlLnByb3RvGiRzdHJ1X3Rl",
            "YW1fYXBwbHlfcGxheWVyX2Rpc3BsYXkucHJvdG8i4QIKFVRlYW1Kb2luQXBw",
            "bHlMaXN0SXRlbRIYCgdhcHBseUlkGAEgASgJUgdhcHBseUlkEjgKCWFwcGx5",
            "VHlwZRgCIAEoDjIaLnpwcm90by5FVGVhbUpvaW5BcHBseVR5cGVSCWFwcGx5",
            "VHlwZRIgCgthcHBsaWNhbnRJZBgDIAEoA1ILYXBwbGljYW50SWQSHAoJYXBw",
            "bHlUaW1lGAQgASgDUglhcHBseVRpbWUSSgoQYXBwbGljYW50RGlzcGxheRgF",
            "IAEoCzIeLnpwcm90by5UZWFtQXBwbHlQbGF5ZXJEaXNwbGF5UhBhcHBsaWNh",
            "bnREaXNwbGF5EiIKDHNvdXJjZVRlYW1JZBgGIAEoA1IMc291cmNlVGVhbUlk",
            "EkQKDWFwcGxpY2FudExpc3QYByADKAsyHi56cHJvdG8uVGVhbUFwcGx5UGxh",
            "eWVyRGlzcGxheVINYXBwbGljYW50TGlzdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumETeamJoinApplyTypeReflection.Descriptor, global::Zproto.StruTeamApplyPlayerDisplayReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.TeamJoinApplyListItem), global::Zproto.TeamJoinApplyListItem.Parser, new[]{ "ApplyId", "ApplyType", "ApplicantId", "ApplyTime", "ApplicantDisplay", "SourceTeamId", "ApplicantList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TeamJoinApplyListItem : pb::IMessage<TeamJoinApplyListItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeamJoinApplyListItem> _parser = new pb::MessageParser<TeamJoinApplyListItem>(() => new TeamJoinApplyListItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeamJoinApplyListItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruTeamJoinApplyListItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamJoinApplyListItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamJoinApplyListItem(TeamJoinApplyListItem other) : this() {
      applyId_ = other.applyId_;
      applyType_ = other.applyType_;
      applicantId_ = other.applicantId_;
      applyTime_ = other.applyTime_;
      applicantDisplay_ = other.applicantDisplay_ != null ? other.applicantDisplay_.Clone() : null;
      sourceTeamId_ = other.sourceTeamId_;
      applicantList_ = other.applicantList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamJoinApplyListItem Clone() {
      return new TeamJoinApplyListItem(this);
    }

    /// <summary>Field number for the "applyId" field.</summary>
    public const int ApplyIdFieldNumber = 1;
    private string applyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApplyId {
      get { return applyId_; }
      set {
        applyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "applyType" field.</summary>
    public const int ApplyTypeFieldNumber = 2;
    private global::Zproto.ETeamJoinApplyType applyType_ = global::Zproto.ETeamJoinApplyType.Personal;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ETeamJoinApplyType ApplyType {
      get { return applyType_; }
      set {
        applyType_ = value;
      }
    }

    /// <summary>Field number for the "applicantId" field.</summary>
    public const int ApplicantIdFieldNumber = 3;
    private long applicantId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ApplicantId {
      get { return applicantId_; }
      set {
        applicantId_ = value;
      }
    }

    /// <summary>Field number for the "applyTime" field.</summary>
    public const int ApplyTimeFieldNumber = 4;
    private long applyTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ApplyTime {
      get { return applyTime_; }
      set {
        applyTime_ = value;
      }
    }

    /// <summary>Field number for the "applicantDisplay" field.</summary>
    public const int ApplicantDisplayFieldNumber = 5;
    private global::Zproto.TeamApplyPlayerDisplay applicantDisplay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.TeamApplyPlayerDisplay ApplicantDisplay {
      get { return applicantDisplay_; }
      set {
        applicantDisplay_ = value;
      }
    }

    /// <summary>Field number for the "sourceTeamId" field.</summary>
    public const int SourceTeamIdFieldNumber = 6;
    private long sourceTeamId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SourceTeamId {
      get { return sourceTeamId_; }
      set {
        sourceTeamId_ = value;
      }
    }

    /// <summary>Field number for the "applicantList" field.</summary>
    public const int ApplicantListFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Zproto.TeamApplyPlayerDisplay> _repeated_applicantList_codec
        = pb::FieldCodec.ForMessage(58, global::Zproto.TeamApplyPlayerDisplay.Parser);
    private readonly pbc::RepeatedField<global::Zproto.TeamApplyPlayerDisplay> applicantList_ = new pbc::RepeatedField<global::Zproto.TeamApplyPlayerDisplay>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zproto.TeamApplyPlayerDisplay> ApplicantList {
      get { return applicantList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeamJoinApplyListItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeamJoinApplyListItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ApplyId != other.ApplyId) return false;
      if (ApplyType != other.ApplyType) return false;
      if (ApplicantId != other.ApplicantId) return false;
      if (ApplyTime != other.ApplyTime) return false;
      if (!object.Equals(ApplicantDisplay, other.ApplicantDisplay)) return false;
      if (SourceTeamId != other.SourceTeamId) return false;
      if(!applicantList_.Equals(other.applicantList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ApplyId.Length != 0) hash ^= ApplyId.GetHashCode();
      if (ApplyType != global::Zproto.ETeamJoinApplyType.Personal) hash ^= ApplyType.GetHashCode();
      if (ApplicantId != 0L) hash ^= ApplicantId.GetHashCode();
      if (ApplyTime != 0L) hash ^= ApplyTime.GetHashCode();
      if (applicantDisplay_ != null) hash ^= ApplicantDisplay.GetHashCode();
      if (SourceTeamId != 0L) hash ^= SourceTeamId.GetHashCode();
      hash ^= applicantList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ApplyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApplyId);
      }
      if (ApplyType != global::Zproto.ETeamJoinApplyType.Personal) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ApplyType);
      }
      if (ApplicantId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ApplicantId);
      }
      if (ApplyTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ApplyTime);
      }
      if (applicantDisplay_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ApplicantDisplay);
      }
      if (SourceTeamId != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(SourceTeamId);
      }
      applicantList_.WriteTo(output, _repeated_applicantList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ApplyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApplyId);
      }
      if (ApplyType != global::Zproto.ETeamJoinApplyType.Personal) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ApplyType);
      }
      if (ApplicantId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(ApplicantId);
      }
      if (ApplyTime != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(ApplyTime);
      }
      if (applicantDisplay_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ApplicantDisplay);
      }
      if (SourceTeamId != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(SourceTeamId);
      }
      applicantList_.WriteTo(ref output, _repeated_applicantList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ApplyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApplyId);
      }
      if (ApplyType != global::Zproto.ETeamJoinApplyType.Personal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ApplyType);
      }
      if (ApplicantId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ApplicantId);
      }
      if (ApplyTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ApplyTime);
      }
      if (applicantDisplay_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ApplicantDisplay);
      }
      if (SourceTeamId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SourceTeamId);
      }
      size += applicantList_.CalculateSize(_repeated_applicantList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeamJoinApplyListItem other) {
      if (other == null) {
        return;
      }
      if (other.ApplyId.Length != 0) {
        ApplyId = other.ApplyId;
      }
      if (other.ApplyType != global::Zproto.ETeamJoinApplyType.Personal) {
        ApplyType = other.ApplyType;
      }
      if (other.ApplicantId != 0L) {
        ApplicantId = other.ApplicantId;
      }
      if (other.ApplyTime != 0L) {
        ApplyTime = other.ApplyTime;
      }
      if (other.applicantDisplay_ != null) {
        if (applicantDisplay_ == null) {
          ApplicantDisplay = new global::Zproto.TeamApplyPlayerDisplay();
        }
        ApplicantDisplay.MergeFrom(other.ApplicantDisplay);
      }
      if (other.SourceTeamId != 0L) {
        SourceTeamId = other.SourceTeamId;
      }
      applicantList_.Add(other.applicantList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ApplyId = input.ReadString();
            break;
          }
          case 16: {
            ApplyType = (global::Zproto.ETeamJoinApplyType) input.ReadEnum();
            break;
          }
          case 24: {
            ApplicantId = input.ReadInt64();
            break;
          }
          case 32: {
            ApplyTime = input.ReadInt64();
            break;
          }
          case 42: {
            if (applicantDisplay_ == null) {
              ApplicantDisplay = new global::Zproto.TeamApplyPlayerDisplay();
            }
            input.ReadMessage(ApplicantDisplay);
            break;
          }
          case 48: {
            SourceTeamId = input.ReadInt64();
            break;
          }
          case 58: {
            applicantList_.AddEntriesFrom(input, _repeated_applicantList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ApplyId = input.ReadString();
            break;
          }
          case 16: {
            ApplyType = (global::Zproto.ETeamJoinApplyType) input.ReadEnum();
            break;
          }
          case 24: {
            ApplicantId = input.ReadInt64();
            break;
          }
          case 32: {
            ApplyTime = input.ReadInt64();
            break;
          }
          case 42: {
            if (applicantDisplay_ == null) {
              ApplicantDisplay = new global::Zproto.TeamApplyPlayerDisplay();
            }
            input.ReadMessage(ApplicantDisplay);
            break;
          }
          case 48: {
            SourceTeamId = input.ReadInt64();
            break;
          }
          case 58: {
            applicantList_.AddEntriesFrom(ref input, _repeated_applicantList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
