// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_leader_board_sub_record.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_leader_board_sub_record.proto</summary>
  public static partial class StruLeaderBoardSubRecordReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_leader_board_sub_record.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruLeaderBoardSubRecordReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJzdHJ1X2xlYWRlcl9ib2FyZF9zdWJfcmVjb3JkLnByb3RvEgZ6cHJvdG8a",
            "H3N0cnVfcGxheWVyX3JhbmtfbWV0YWRhdGEucHJvdG8imAIKFExlYWRlckJv",
            "YXJkU3ViUmVjb3JkEh4KCnN1YkJvYXJkSWQYASABKAVSCnN1YkJvYXJkSWQS",
            "GgoIcmFua0RhdGEYAiADKANSCHJhbmtEYXRhEhwKCXNob3dQYXJhbRgDIAMo",
            "CVIJc2hvd1BhcmFtEjQKB21lbWJlcnMYBCADKAsyGi56cHJvdG8uUGxheWVy",
            "UmFua01ldGFkYXRhUgdtZW1iZXJzEhwKCXN1YmplY3RJZBgFIAEoCVIJc3Vi",
            "amVjdElkEiwKEWR1bmdlb25EaWZmaWN1bHR5GAYgASgFUhFkdW5nZW9uRGlm",
            "ZmljdWx0eRIkCg1wYXNzVGltZVBvaW50GAcgASgDUg1wYXNzVGltZVBvaW50",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruPlayerRankMetadataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.LeaderBoardSubRecord), global::Zproto.LeaderBoardSubRecord.Parser, new[]{ "SubBoardId", "RankData", "ShowParam", "Members", "SubjectId", "DungeonDifficulty", "PassTimePoint" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LeaderBoardSubRecord : pb::IMessage<LeaderBoardSubRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LeaderBoardSubRecord> _parser = new pb::MessageParser<LeaderBoardSubRecord>(() => new LeaderBoardSubRecord());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LeaderBoardSubRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruLeaderBoardSubRecordReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardSubRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardSubRecord(LeaderBoardSubRecord other) : this() {
      subBoardId_ = other.subBoardId_;
      rankData_ = other.rankData_.Clone();
      showParam_ = other.showParam_.Clone();
      members_ = other.members_.Clone();
      subjectId_ = other.subjectId_;
      dungeonDifficulty_ = other.dungeonDifficulty_;
      passTimePoint_ = other.passTimePoint_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardSubRecord Clone() {
      return new LeaderBoardSubRecord(this);
    }

    /// <summary>Field number for the "subBoardId" field.</summary>
    public const int SubBoardIdFieldNumber = 1;
    private int subBoardId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SubBoardId {
      get { return subBoardId_; }
      set {
        subBoardId_ = value;
      }
    }

    /// <summary>Field number for the "rankData" field.</summary>
    public const int RankDataFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_rankData_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> rankData_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> RankData {
      get { return rankData_; }
    }

    /// <summary>Field number for the "showParam" field.</summary>
    public const int ShowParamFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_showParam_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> showParam_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ShowParam {
      get { return showParam_; }
    }

    /// <summary>Field number for the "members" field.</summary>
    public const int MembersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Zproto.PlayerRankMetadata> _repeated_members_codec
        = pb::FieldCodec.ForMessage(34, global::Zproto.PlayerRankMetadata.Parser);
    private readonly pbc::RepeatedField<global::Zproto.PlayerRankMetadata> members_ = new pbc::RepeatedField<global::Zproto.PlayerRankMetadata>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zproto.PlayerRankMetadata> Members {
      get { return members_; }
    }

    /// <summary>Field number for the "subjectId" field.</summary>
    public const int SubjectIdFieldNumber = 5;
    private string subjectId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubjectId {
      get { return subjectId_; }
      set {
        subjectId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dungeonDifficulty" field.</summary>
    public const int DungeonDifficultyFieldNumber = 6;
    private int dungeonDifficulty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DungeonDifficulty {
      get { return dungeonDifficulty_; }
      set {
        dungeonDifficulty_ = value;
      }
    }

    /// <summary>Field number for the "passTimePoint" field.</summary>
    public const int PassTimePointFieldNumber = 7;
    private long passTimePoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PassTimePoint {
      get { return passTimePoint_; }
      set {
        passTimePoint_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LeaderBoardSubRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LeaderBoardSubRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SubBoardId != other.SubBoardId) return false;
      if(!rankData_.Equals(other.rankData_)) return false;
      if(!showParam_.Equals(other.showParam_)) return false;
      if(!members_.Equals(other.members_)) return false;
      if (SubjectId != other.SubjectId) return false;
      if (DungeonDifficulty != other.DungeonDifficulty) return false;
      if (PassTimePoint != other.PassTimePoint) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SubBoardId != 0) hash ^= SubBoardId.GetHashCode();
      hash ^= rankData_.GetHashCode();
      hash ^= showParam_.GetHashCode();
      hash ^= members_.GetHashCode();
      if (SubjectId.Length != 0) hash ^= SubjectId.GetHashCode();
      if (DungeonDifficulty != 0) hash ^= DungeonDifficulty.GetHashCode();
      if (PassTimePoint != 0L) hash ^= PassTimePoint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SubBoardId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SubBoardId);
      }
      rankData_.WriteTo(output, _repeated_rankData_codec);
      showParam_.WriteTo(output, _repeated_showParam_codec);
      members_.WriteTo(output, _repeated_members_codec);
      if (SubjectId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SubjectId);
      }
      if (DungeonDifficulty != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(DungeonDifficulty);
      }
      if (PassTimePoint != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(PassTimePoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SubBoardId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SubBoardId);
      }
      rankData_.WriteTo(ref output, _repeated_rankData_codec);
      showParam_.WriteTo(ref output, _repeated_showParam_codec);
      members_.WriteTo(ref output, _repeated_members_codec);
      if (SubjectId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SubjectId);
      }
      if (DungeonDifficulty != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(DungeonDifficulty);
      }
      if (PassTimePoint != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(PassTimePoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SubBoardId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SubBoardId);
      }
      size += rankData_.CalculateSize(_repeated_rankData_codec);
      size += showParam_.CalculateSize(_repeated_showParam_codec);
      size += members_.CalculateSize(_repeated_members_codec);
      if (SubjectId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubjectId);
      }
      if (DungeonDifficulty != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DungeonDifficulty);
      }
      if (PassTimePoint != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PassTimePoint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LeaderBoardSubRecord other) {
      if (other == null) {
        return;
      }
      if (other.SubBoardId != 0) {
        SubBoardId = other.SubBoardId;
      }
      rankData_.Add(other.rankData_);
      showParam_.Add(other.showParam_);
      members_.Add(other.members_);
      if (other.SubjectId.Length != 0) {
        SubjectId = other.SubjectId;
      }
      if (other.DungeonDifficulty != 0) {
        DungeonDifficulty = other.DungeonDifficulty;
      }
      if (other.PassTimePoint != 0L) {
        PassTimePoint = other.PassTimePoint;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SubBoardId = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            rankData_.AddEntriesFrom(input, _repeated_rankData_codec);
            break;
          }
          case 26: {
            showParam_.AddEntriesFrom(input, _repeated_showParam_codec);
            break;
          }
          case 34: {
            members_.AddEntriesFrom(input, _repeated_members_codec);
            break;
          }
          case 42: {
            SubjectId = input.ReadString();
            break;
          }
          case 48: {
            DungeonDifficulty = input.ReadInt32();
            break;
          }
          case 56: {
            PassTimePoint = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SubBoardId = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            rankData_.AddEntriesFrom(ref input, _repeated_rankData_codec);
            break;
          }
          case 26: {
            showParam_.AddEntriesFrom(ref input, _repeated_showParam_codec);
            break;
          }
          case 34: {
            members_.AddEntriesFrom(ref input, _repeated_members_codec);
            break;
          }
          case 42: {
            SubjectId = input.ReadString();
            break;
          }
          case 48: {
            DungeonDifficulty = input.ReadInt32();
            break;
          }
          case 56: {
            PassTimePoint = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
