// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_get_my_rank_reply.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_get_my_rank_reply.proto</summary>
  public static partial class StruGetMyRankReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_get_my_rank_reply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruGetMyRankReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxzdHJ1X2dldF9teV9yYW5rX3JlcGx5LnByb3RvEgZ6cHJvdG8aF2VudW1f",
            "ZV9lcnJvcl9jb2RlLnByb3RvGh5zdHJ1X2xlYWRlcl9ib2FyZF9yZWNvcmQu",
            "cHJvdG8inQEKDkdldE15UmFua1JlcGx5EiYKDnNlbGZUb3BQZXJjZW50GAEg",
            "ASgFUg5zZWxmVG9wUGVyY2VudBI1CghteVJlY29yZBgCIAEoCzIZLnpwcm90",
            "by5MZWFkZXJCb2FyZFJlY29yZFIIbXlSZWNvcmQSLAoHZXJyQ29kZRgDIAEo",
            "DjISLnpwcm90by5FRXJyb3JDb2RlUgdlcnJDb2RlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEErrorCodeReflection.Descriptor, global::Zproto.StruLeaderBoardRecordReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.GetMyRankReply), global::Zproto.GetMyRankReply.Parser, new[]{ "SelfTopPercent", "MyRecord", "ErrCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetMyRankReply : pb::IMessage<GetMyRankReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetMyRankReply> _parser = new pb::MessageParser<GetMyRankReply>(() => new GetMyRankReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetMyRankReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruGetMyRankReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetMyRankReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetMyRankReply(GetMyRankReply other) : this() {
      selfTopPercent_ = other.selfTopPercent_;
      myRecord_ = other.myRecord_ != null ? other.myRecord_.Clone() : null;
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetMyRankReply Clone() {
      return new GetMyRankReply(this);
    }

    /// <summary>Field number for the "selfTopPercent" field.</summary>
    public const int SelfTopPercentFieldNumber = 1;
    private int selfTopPercent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SelfTopPercent {
      get { return selfTopPercent_; }
      set {
        selfTopPercent_ = value;
      }
    }

    /// <summary>Field number for the "myRecord" field.</summary>
    public const int MyRecordFieldNumber = 2;
    private global::Zproto.LeaderBoardRecord myRecord_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.LeaderBoardRecord MyRecord {
      get { return myRecord_; }
      set {
        myRecord_ = value;
      }
    }

    /// <summary>Field number for the "errCode" field.</summary>
    public const int ErrCodeFieldNumber = 3;
    private global::Zproto.EErrorCode errCode_ = global::Zproto.EErrorCode.ErrSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetMyRankReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetMyRankReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SelfTopPercent != other.SelfTopPercent) return false;
      if (!object.Equals(MyRecord, other.MyRecord)) return false;
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SelfTopPercent != 0) hash ^= SelfTopPercent.GetHashCode();
      if (myRecord_ != null) hash ^= MyRecord.GetHashCode();
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SelfTopPercent != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SelfTopPercent);
      }
      if (myRecord_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MyRecord);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SelfTopPercent != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SelfTopPercent);
      }
      if (myRecord_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(MyRecord);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SelfTopPercent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SelfTopPercent);
      }
      if (myRecord_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MyRecord);
      }
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetMyRankReply other) {
      if (other == null) {
        return;
      }
      if (other.SelfTopPercent != 0) {
        SelfTopPercent = other.SelfTopPercent;
      }
      if (other.myRecord_ != null) {
        if (myRecord_ == null) {
          MyRecord = new global::Zproto.LeaderBoardRecord();
        }
        MyRecord.MergeFrom(other.MyRecord);
      }
      if (other.ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SelfTopPercent = input.ReadInt32();
            break;
          }
          case 18: {
            if (myRecord_ == null) {
              MyRecord = new global::Zproto.LeaderBoardRecord();
            }
            input.ReadMessage(MyRecord);
            break;
          }
          case 24: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SelfTopPercent = input.ReadInt32();
            break;
          }
          case 18: {
            if (myRecord_ == null) {
              MyRecord = new global::Zproto.LeaderBoardRecord();
            }
            input.ReadMessage(MyRecord);
            break;
          }
          case 24: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
