// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_query_team_list_reply.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_query_team_list_reply.proto</summary>
  public static partial class StruQueryTeamListReplyReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_query_team_list_reply.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruQueryTeamListReplyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBzdHJ1X3F1ZXJ5X3RlYW1fbGlzdF9yZXBseS5wcm90bxIGenByb3RvGhdl",
            "bnVtX2VfZXJyb3JfY29kZS5wcm90bxoec3RydV90ZWFtX2xpc3Rfc2hvd19p",
            "bmZvLnByb3RvItYDChJRdWVyeVRlYW1MaXN0UmVwbHkSGgoIdGFyZ2V0SWQY",
            "ASABKAVSCHRhcmdldElkEhgKB3NjZW5lSWQYAiABKAVSB3NjZW5lSWQSJgoO",
            "bWluTWVtYmVyQ291bnQYAyABKAVSDm1pbk1lbWJlckNvdW50EiYKDm1heE1l",
            "bWJlckNvdW50GAQgASgFUg5tYXhNZW1iZXJDb3VudBIiCgxhYmlsaXR5U2Nv",
            "cmUYBSABKAVSDGFiaWxpdHlTY29yZRIuChJzZWFzb25BYmlsaXR5U2NvcmUY",
            "BiABKAVSEnNlYXNvbkFiaWxpdHlTY29yZRIgCgtxdWVyeVRhbGVudBgHIAEo",
            "BVILcXVlcnlUYWxlbnQSHAoJcGFnZUluZGV4GAggASgFUglwYWdlSW5kZXgS",
            "GgoIcGFnZVNpemUYCSABKAVSCHBhZ2VTaXplEiYKDnBhZ2VUb3RhbENvdW50",
            "GAogASgFUg5wYWdlVG90YWxDb3VudBI0Cgh0ZWFtTGlzdBgLIAMoCzIYLnpw",
            "cm90by5UZWFtTGlzdFNob3dJbmZvUgh0ZWFtTGlzdBIsCgdlcnJDb2RlGAwg",
            "ASgOMhIuenByb3RvLkVFcnJvckNvZGVSB2VyckNvZGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumEErrorCodeReflection.Descriptor, global::Zproto.StruTeamListShowInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.QueryTeamListReply), global::Zproto.QueryTeamListReply.Parser, new[]{ "TargetId", "SceneId", "MinMemberCount", "MaxMemberCount", "AbilityScore", "SeasonAbilityScore", "QueryTalent", "PageIndex", "PageSize", "PageTotalCount", "TeamList", "ErrCode" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class QueryTeamListReply : pb::IMessage<QueryTeamListReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryTeamListReply> _parser = new pb::MessageParser<QueryTeamListReply>(() => new QueryTeamListReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryTeamListReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruQueryTeamListReplyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryTeamListReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryTeamListReply(QueryTeamListReply other) : this() {
      targetId_ = other.targetId_;
      sceneId_ = other.sceneId_;
      minMemberCount_ = other.minMemberCount_;
      maxMemberCount_ = other.maxMemberCount_;
      abilityScore_ = other.abilityScore_;
      seasonAbilityScore_ = other.seasonAbilityScore_;
      queryTalent_ = other.queryTalent_;
      pageIndex_ = other.pageIndex_;
      pageSize_ = other.pageSize_;
      pageTotalCount_ = other.pageTotalCount_;
      teamList_ = other.teamList_.Clone();
      errCode_ = other.errCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryTeamListReply Clone() {
      return new QueryTeamListReply(this);
    }

    /// <summary>Field number for the "targetId" field.</summary>
    public const int TargetIdFieldNumber = 1;
    private int targetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "sceneId" field.</summary>
    public const int SceneIdFieldNumber = 2;
    private int sceneId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneId {
      get { return sceneId_; }
      set {
        sceneId_ = value;
      }
    }

    /// <summary>Field number for the "minMemberCount" field.</summary>
    public const int MinMemberCountFieldNumber = 3;
    private int minMemberCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MinMemberCount {
      get { return minMemberCount_; }
      set {
        minMemberCount_ = value;
      }
    }

    /// <summary>Field number for the "maxMemberCount" field.</summary>
    public const int MaxMemberCountFieldNumber = 4;
    private int maxMemberCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxMemberCount {
      get { return maxMemberCount_; }
      set {
        maxMemberCount_ = value;
      }
    }

    /// <summary>Field number for the "abilityScore" field.</summary>
    public const int AbilityScoreFieldNumber = 5;
    private int abilityScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AbilityScore {
      get { return abilityScore_; }
      set {
        abilityScore_ = value;
      }
    }

    /// <summary>Field number for the "seasonAbilityScore" field.</summary>
    public const int SeasonAbilityScoreFieldNumber = 6;
    private int seasonAbilityScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonAbilityScore {
      get { return seasonAbilityScore_; }
      set {
        seasonAbilityScore_ = value;
      }
    }

    /// <summary>Field number for the "queryTalent" field.</summary>
    public const int QueryTalentFieldNumber = 7;
    private int queryTalent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int QueryTalent {
      get { return queryTalent_; }
      set {
        queryTalent_ = value;
      }
    }

    /// <summary>Field number for the "pageIndex" field.</summary>
    public const int PageIndexFieldNumber = 8;
    private int pageIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PageIndex {
      get { return pageIndex_; }
      set {
        pageIndex_ = value;
      }
    }

    /// <summary>Field number for the "pageSize" field.</summary>
    public const int PageSizeFieldNumber = 9;
    private int pageSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    /// <summary>Field number for the "pageTotalCount" field.</summary>
    public const int PageTotalCountFieldNumber = 10;
    private int pageTotalCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PageTotalCount {
      get { return pageTotalCount_; }
      set {
        pageTotalCount_ = value;
      }
    }

    /// <summary>Field number for the "teamList" field.</summary>
    public const int TeamListFieldNumber = 11;
    private static readonly pb::FieldCodec<global::Zproto.TeamListShowInfo> _repeated_teamList_codec
        = pb::FieldCodec.ForMessage(90, global::Zproto.TeamListShowInfo.Parser);
    private readonly pbc::RepeatedField<global::Zproto.TeamListShowInfo> teamList_ = new pbc::RepeatedField<global::Zproto.TeamListShowInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zproto.TeamListShowInfo> TeamList {
      get { return teamList_; }
    }

    /// <summary>Field number for the "errCode" field.</summary>
    public const int ErrCodeFieldNumber = 12;
    private global::Zproto.EErrorCode errCode_ = global::Zproto.EErrorCode.ErrSuccess;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.EErrorCode ErrCode {
      get { return errCode_; }
      set {
        errCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryTeamListReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryTeamListReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TargetId != other.TargetId) return false;
      if (SceneId != other.SceneId) return false;
      if (MinMemberCount != other.MinMemberCount) return false;
      if (MaxMemberCount != other.MaxMemberCount) return false;
      if (AbilityScore != other.AbilityScore) return false;
      if (SeasonAbilityScore != other.SeasonAbilityScore) return false;
      if (QueryTalent != other.QueryTalent) return false;
      if (PageIndex != other.PageIndex) return false;
      if (PageSize != other.PageSize) return false;
      if (PageTotalCount != other.PageTotalCount) return false;
      if(!teamList_.Equals(other.teamList_)) return false;
      if (ErrCode != other.ErrCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TargetId != 0) hash ^= TargetId.GetHashCode();
      if (SceneId != 0) hash ^= SceneId.GetHashCode();
      if (MinMemberCount != 0) hash ^= MinMemberCount.GetHashCode();
      if (MaxMemberCount != 0) hash ^= MaxMemberCount.GetHashCode();
      if (AbilityScore != 0) hash ^= AbilityScore.GetHashCode();
      if (SeasonAbilityScore != 0) hash ^= SeasonAbilityScore.GetHashCode();
      if (QueryTalent != 0) hash ^= QueryTalent.GetHashCode();
      if (PageIndex != 0) hash ^= PageIndex.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      if (PageTotalCount != 0) hash ^= PageTotalCount.GetHashCode();
      hash ^= teamList_.GetHashCode();
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) hash ^= ErrCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TargetId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TargetId);
      }
      if (SceneId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SceneId);
      }
      if (MinMemberCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MinMemberCount);
      }
      if (MaxMemberCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MaxMemberCount);
      }
      if (AbilityScore != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AbilityScore);
      }
      if (SeasonAbilityScore != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeasonAbilityScore);
      }
      if (QueryTalent != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(QueryTalent);
      }
      if (PageIndex != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(PageIndex);
      }
      if (PageSize != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(PageSize);
      }
      if (PageTotalCount != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(PageTotalCount);
      }
      teamList_.WriteTo(output, _repeated_teamList_codec);
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(96);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TargetId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TargetId);
      }
      if (SceneId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SceneId);
      }
      if (MinMemberCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MinMemberCount);
      }
      if (MaxMemberCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MaxMemberCount);
      }
      if (AbilityScore != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(AbilityScore);
      }
      if (SeasonAbilityScore != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeasonAbilityScore);
      }
      if (QueryTalent != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(QueryTalent);
      }
      if (PageIndex != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(PageIndex);
      }
      if (PageSize != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(PageSize);
      }
      if (PageTotalCount != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(PageTotalCount);
      }
      teamList_.WriteTo(ref output, _repeated_teamList_codec);
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        output.WriteRawTag(96);
        output.WriteEnum((int) ErrCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TargetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetId);
      }
      if (SceneId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneId);
      }
      if (MinMemberCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MinMemberCount);
      }
      if (MaxMemberCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxMemberCount);
      }
      if (AbilityScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AbilityScore);
      }
      if (SeasonAbilityScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonAbilityScore);
      }
      if (QueryTalent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QueryTalent);
      }
      if (PageIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageIndex);
      }
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      if (PageTotalCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageTotalCount);
      }
      size += teamList_.CalculateSize(_repeated_teamList_codec);
      if (ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryTeamListReply other) {
      if (other == null) {
        return;
      }
      if (other.TargetId != 0) {
        TargetId = other.TargetId;
      }
      if (other.SceneId != 0) {
        SceneId = other.SceneId;
      }
      if (other.MinMemberCount != 0) {
        MinMemberCount = other.MinMemberCount;
      }
      if (other.MaxMemberCount != 0) {
        MaxMemberCount = other.MaxMemberCount;
      }
      if (other.AbilityScore != 0) {
        AbilityScore = other.AbilityScore;
      }
      if (other.SeasonAbilityScore != 0) {
        SeasonAbilityScore = other.SeasonAbilityScore;
      }
      if (other.QueryTalent != 0) {
        QueryTalent = other.QueryTalent;
      }
      if (other.PageIndex != 0) {
        PageIndex = other.PageIndex;
      }
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
      if (other.PageTotalCount != 0) {
        PageTotalCount = other.PageTotalCount;
      }
      teamList_.Add(other.teamList_);
      if (other.ErrCode != global::Zproto.EErrorCode.ErrSuccess) {
        ErrCode = other.ErrCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TargetId = input.ReadInt32();
            break;
          }
          case 16: {
            SceneId = input.ReadInt32();
            break;
          }
          case 24: {
            MinMemberCount = input.ReadInt32();
            break;
          }
          case 32: {
            MaxMemberCount = input.ReadInt32();
            break;
          }
          case 40: {
            AbilityScore = input.ReadInt32();
            break;
          }
          case 48: {
            SeasonAbilityScore = input.ReadInt32();
            break;
          }
          case 56: {
            QueryTalent = input.ReadInt32();
            break;
          }
          case 64: {
            PageIndex = input.ReadInt32();
            break;
          }
          case 72: {
            PageSize = input.ReadInt32();
            break;
          }
          case 80: {
            PageTotalCount = input.ReadInt32();
            break;
          }
          case 90: {
            teamList_.AddEntriesFrom(input, _repeated_teamList_codec);
            break;
          }
          case 96: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TargetId = input.ReadInt32();
            break;
          }
          case 16: {
            SceneId = input.ReadInt32();
            break;
          }
          case 24: {
            MinMemberCount = input.ReadInt32();
            break;
          }
          case 32: {
            MaxMemberCount = input.ReadInt32();
            break;
          }
          case 40: {
            AbilityScore = input.ReadInt32();
            break;
          }
          case 48: {
            SeasonAbilityScore = input.ReadInt32();
            break;
          }
          case 56: {
            QueryTalent = input.ReadInt32();
            break;
          }
          case 64: {
            PageIndex = input.ReadInt32();
            break;
          }
          case 72: {
            PageSize = input.ReadInt32();
            break;
          }
          case 80: {
            PageTotalCount = input.ReadInt32();
            break;
          }
          case 90: {
            teamList_.AddEntriesFrom(ref input, _repeated_teamList_codec);
            break;
          }
          case 96: {
            ErrCode = (global::Zproto.EErrorCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
