// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_player_rank_metadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_player_rank_metadata.proto</summary>
  public static partial class StruPlayerRankMetadataReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_player_rank_metadata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruPlayerRankMetadataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9zdHJ1X3BsYXllcl9yYW5rX21ldGFkYXRhLnByb3RvEgZ6cHJvdG8aGnN0",
            "cnVfcHJvZmVzc2lvbl9kYXRhLnByb3RvItgBChJQbGF5ZXJSYW5rTWV0YWRh",
            "dGESFgoGY2hhcklkGAEgASgDUgZjaGFySWQSEgoEbmFtZRgCIAEoCVIEbmFt",
            "ZRI+Cg5wcm9mZXNzaW9uRGF0YRgEIAEoCzIWLnpwcm90by5Qcm9mZXNzaW9u",
            "RGF0YVIOcHJvZmVzc2lvbkRhdGESFAoFbGV2ZWwYBSABKAVSBWxldmVsEhoK",
            "CHdlYXBvbklkGAYgASgFUgh3ZWFwb25JZBIkCg10YWxlbnRTdGFnZUlkGAcg",
            "ASgFUg10YWxlbnRTdGFnZUlkYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruProfessionDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.PlayerRankMetadata), global::Zproto.PlayerRankMetadata.Parser, new[]{ "CharId", "Name", "ProfessionData", "Level", "WeaponId", "TalentStageId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerRankMetadata : pb::IMessage<PlayerRankMetadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerRankMetadata> _parser = new pb::MessageParser<PlayerRankMetadata>(() => new PlayerRankMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerRankMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruPlayerRankMetadataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerRankMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerRankMetadata(PlayerRankMetadata other) : this() {
      charId_ = other.charId_;
      name_ = other.name_;
      professionData_ = other.professionData_ != null ? other.professionData_.Clone() : null;
      level_ = other.level_;
      weaponId_ = other.weaponId_;
      talentStageId_ = other.talentStageId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerRankMetadata Clone() {
      return new PlayerRankMetadata(this);
    }

    /// <summary>Field number for the "charId" field.</summary>
    public const int CharIdFieldNumber = 1;
    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { return charId_; }
      set {
        charId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "professionData" field.</summary>
    public const int ProfessionDataFieldNumber = 4;
    private global::Zproto.ProfessionData professionData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ProfessionData ProfessionData {
      get { return professionData_; }
      set {
        professionData_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 5;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "weaponId" field.</summary>
    public const int WeaponIdFieldNumber = 6;
    private int weaponId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WeaponId {
      get { return weaponId_; }
      set {
        weaponId_ = value;
      }
    }

    /// <summary>Field number for the "talentStageId" field.</summary>
    public const int TalentStageIdFieldNumber = 7;
    private int talentStageId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TalentStageId {
      get { return talentStageId_; }
      set {
        talentStageId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerRankMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerRankMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharId != other.CharId) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(ProfessionData, other.ProfessionData)) return false;
      if (Level != other.Level) return false;
      if (WeaponId != other.WeaponId) return false;
      if (TalentStageId != other.TalentStageId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharId != 0L) hash ^= CharId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (professionData_ != null) hash ^= ProfessionData.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (WeaponId != 0) hash ^= WeaponId.GetHashCode();
      if (TalentStageId != 0) hash ^= TalentStageId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (professionData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ProfessionData);
      }
      if (Level != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Level);
      }
      if (WeaponId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(WeaponId);
      }
      if (TalentStageId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(TalentStageId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (professionData_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ProfessionData);
      }
      if (Level != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Level);
      }
      if (WeaponId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(WeaponId);
      }
      if (TalentStageId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(TalentStageId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (professionData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProfessionData);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (WeaponId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WeaponId);
      }
      if (TalentStageId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TalentStageId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerRankMetadata other) {
      if (other == null) {
        return;
      }
      if (other.CharId != 0L) {
        CharId = other.CharId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.professionData_ != null) {
        if (professionData_ == null) {
          ProfessionData = new global::Zproto.ProfessionData();
        }
        ProfessionData.MergeFrom(other.ProfessionData);
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.WeaponId != 0) {
        WeaponId = other.WeaponId;
      }
      if (other.TalentStageId != 0) {
        TalentStageId = other.TalentStageId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            if (professionData_ == null) {
              ProfessionData = new global::Zproto.ProfessionData();
            }
            input.ReadMessage(ProfessionData);
            break;
          }
          case 40: {
            Level = input.ReadInt32();
            break;
          }
          case 48: {
            WeaponId = input.ReadInt32();
            break;
          }
          case 56: {
            TalentStageId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            if (professionData_ == null) {
              ProfessionData = new global::Zproto.ProfessionData();
            }
            input.ReadMessage(ProfessionData);
            break;
          }
          case 40: {
            Level = input.ReadInt32();
            break;
          }
          case 48: {
            WeaponId = input.ReadInt32();
            break;
          }
          case 56: {
            TalentStageId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
