// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_leader_board_history_cycle_info.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_leader_board_history_cycle_info.proto</summary>
  public static partial class StruLeaderBoardHistoryCycleInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_leader_board_history_cycle_info.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruLeaderBoardHistoryCycleInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipzdHJ1X2xlYWRlcl9ib2FyZF9oaXN0b3J5X2N5Y2xlX2luZm8ucHJvdG8S",
            "Bnpwcm90byKbAQobTGVhZGVyQm9hcmRIaXN0b3J5Q3ljbGVJbmZvEhoKCGN5",
            "Y2xlS2V5GAEgASgDUghjeWNsZUtleRIeCgpzZXR0bGVUaW1lGAIgASgDUgpz",
            "ZXR0bGVUaW1lEiAKC3JlY29yZENvdW50GAMgASgFUgtyZWNvcmRDb3VudBIe",
            "CgpjeWNsZUNvdW50GAQgASgFUgpjeWNsZUNvdW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.LeaderBoardHistoryCycleInfo), global::Zproto.LeaderBoardHistoryCycleInfo.Parser, new[]{ "CycleKey", "SettleTime", "RecordCount", "CycleCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LeaderBoardHistoryCycleInfo : pb::IMessage<LeaderBoardHistoryCycleInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LeaderBoardHistoryCycleInfo> _parser = new pb::MessageParser<LeaderBoardHistoryCycleInfo>(() => new LeaderBoardHistoryCycleInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LeaderBoardHistoryCycleInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruLeaderBoardHistoryCycleInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardHistoryCycleInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardHistoryCycleInfo(LeaderBoardHistoryCycleInfo other) : this() {
      cycleKey_ = other.cycleKey_;
      settleTime_ = other.settleTime_;
      recordCount_ = other.recordCount_;
      cycleCount_ = other.cycleCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaderBoardHistoryCycleInfo Clone() {
      return new LeaderBoardHistoryCycleInfo(this);
    }

    /// <summary>Field number for the "cycleKey" field.</summary>
    public const int CycleKeyFieldNumber = 1;
    private long cycleKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CycleKey {
      get { return cycleKey_; }
      set {
        cycleKey_ = value;
      }
    }

    /// <summary>Field number for the "settleTime" field.</summary>
    public const int SettleTimeFieldNumber = 2;
    private long settleTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SettleTime {
      get { return settleTime_; }
      set {
        settleTime_ = value;
      }
    }

    /// <summary>Field number for the "recordCount" field.</summary>
    public const int RecordCountFieldNumber = 3;
    private int recordCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RecordCount {
      get { return recordCount_; }
      set {
        recordCount_ = value;
      }
    }

    /// <summary>Field number for the "cycleCount" field.</summary>
    public const int CycleCountFieldNumber = 4;
    private int cycleCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CycleCount {
      get { return cycleCount_; }
      set {
        cycleCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LeaderBoardHistoryCycleInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LeaderBoardHistoryCycleInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CycleKey != other.CycleKey) return false;
      if (SettleTime != other.SettleTime) return false;
      if (RecordCount != other.RecordCount) return false;
      if (CycleCount != other.CycleCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CycleKey != 0L) hash ^= CycleKey.GetHashCode();
      if (SettleTime != 0L) hash ^= SettleTime.GetHashCode();
      if (RecordCount != 0) hash ^= RecordCount.GetHashCode();
      if (CycleCount != 0) hash ^= CycleCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CycleKey != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CycleKey);
      }
      if (SettleTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SettleTime);
      }
      if (RecordCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RecordCount);
      }
      if (CycleCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CycleCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CycleKey != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CycleKey);
      }
      if (SettleTime != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SettleTime);
      }
      if (RecordCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RecordCount);
      }
      if (CycleCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CycleCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CycleKey != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CycleKey);
      }
      if (SettleTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SettleTime);
      }
      if (RecordCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RecordCount);
      }
      if (CycleCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CycleCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LeaderBoardHistoryCycleInfo other) {
      if (other == null) {
        return;
      }
      if (other.CycleKey != 0L) {
        CycleKey = other.CycleKey;
      }
      if (other.SettleTime != 0L) {
        SettleTime = other.SettleTime;
      }
      if (other.RecordCount != 0) {
        RecordCount = other.RecordCount;
      }
      if (other.CycleCount != 0) {
        CycleCount = other.CycleCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CycleKey = input.ReadInt64();
            break;
          }
          case 16: {
            SettleTime = input.ReadInt64();
            break;
          }
          case 24: {
            RecordCount = input.ReadInt32();
            break;
          }
          case 32: {
            CycleCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CycleKey = input.ReadInt64();
            break;
          }
          case 16: {
            SettleTime = input.ReadInt64();
            break;
          }
          case 24: {
            RecordCount = input.ReadInt32();
            break;
          }
          case 32: {
            CycleCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
