// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_get_leader_board_data_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_get_leader_board_data_request.proto</summary>
  public static partial class StruGetLeaderBoardDataRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_get_leader_board_data_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruGetLeaderBoardDataRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihzdHJ1X2dldF9sZWFkZXJfYm9hcmRfZGF0YV9yZXF1ZXN0LnByb3RvEgZ6",
            "cHJvdG8iiwEKGUdldExlYWRlckJvYXJkRGF0YVJlcXVlc3QSJAoNbGVhZGVy",
            "Qm9hcmRJZBgCIAEoBVINbGVhZGVyQm9hcmRJZBIaCghjeWNsZUtleRgDIAEo",
            "A1IIY3ljbGVLZXkSFgoGb2Zmc2V0GAQgASgFUgZvZmZzZXQSFAoFbGltaXQY",
            "BSABKAVSBWxpbWl0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.GetLeaderBoardDataRequest), global::Zproto.GetLeaderBoardDataRequest.Parser, new[]{ "LeaderBoardId", "CycleKey", "Offset", "Limit" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetLeaderBoardDataRequest : pb::IMessage<GetLeaderBoardDataRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetLeaderBoardDataRequest> _parser = new pb::MessageParser<GetLeaderBoardDataRequest>(() => new GetLeaderBoardDataRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetLeaderBoardDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruGetLeaderBoardDataRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLeaderBoardDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLeaderBoardDataRequest(GetLeaderBoardDataRequest other) : this() {
      leaderBoardId_ = other.leaderBoardId_;
      cycleKey_ = other.cycleKey_;
      offset_ = other.offset_;
      limit_ = other.limit_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLeaderBoardDataRequest Clone() {
      return new GetLeaderBoardDataRequest(this);
    }

    /// <summary>Field number for the "leaderBoardId" field.</summary>
    public const int LeaderBoardIdFieldNumber = 2;
    private int leaderBoardId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LeaderBoardId {
      get { return leaderBoardId_; }
      set {
        leaderBoardId_ = value;
      }
    }

    /// <summary>Field number for the "cycleKey" field.</summary>
    public const int CycleKeyFieldNumber = 3;
    private long cycleKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CycleKey {
      get { return cycleKey_; }
      set {
        cycleKey_ = value;
      }
    }

    /// <summary>Field number for the "offset" field.</summary>
    public const int OffsetFieldNumber = 4;
    private int offset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Offset {
      get { return offset_; }
      set {
        offset_ = value;
      }
    }

    /// <summary>Field number for the "limit" field.</summary>
    public const int LimitFieldNumber = 5;
    private int limit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Limit {
      get { return limit_; }
      set {
        limit_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetLeaderBoardDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetLeaderBoardDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LeaderBoardId != other.LeaderBoardId) return false;
      if (CycleKey != other.CycleKey) return false;
      if (Offset != other.Offset) return false;
      if (Limit != other.Limit) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LeaderBoardId != 0) hash ^= LeaderBoardId.GetHashCode();
      if (CycleKey != 0L) hash ^= CycleKey.GetHashCode();
      if (Offset != 0) hash ^= Offset.GetHashCode();
      if (Limit != 0) hash ^= Limit.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LeaderBoardId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LeaderBoardId);
      }
      if (CycleKey != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CycleKey);
      }
      if (Offset != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Offset);
      }
      if (Limit != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Limit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LeaderBoardId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LeaderBoardId);
      }
      if (CycleKey != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CycleKey);
      }
      if (Offset != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Offset);
      }
      if (Limit != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Limit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LeaderBoardId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LeaderBoardId);
      }
      if (CycleKey != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CycleKey);
      }
      if (Offset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
      }
      if (Limit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Limit);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetLeaderBoardDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.LeaderBoardId != 0) {
        LeaderBoardId = other.LeaderBoardId;
      }
      if (other.CycleKey != 0L) {
        CycleKey = other.CycleKey;
      }
      if (other.Offset != 0) {
        Offset = other.Offset;
      }
      if (other.Limit != 0) {
        Limit = other.Limit;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            LeaderBoardId = input.ReadInt32();
            break;
          }
          case 24: {
            CycleKey = input.ReadInt64();
            break;
          }
          case 32: {
            Offset = input.ReadInt32();
            break;
          }
          case 40: {
            Limit = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            LeaderBoardId = input.ReadInt32();
            break;
          }
          case 24: {
            CycleKey = input.ReadInt64();
            break;
          }
          case 32: {
            Offset = input.ReadInt32();
            break;
          }
          case 40: {
            Limit = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
