// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_team_apply_player_display.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_team_apply_player_display.proto</summary>
  public static partial class StruTeamApplyPlayerDisplayReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_team_apply_player_display.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruTeamApplyPlayerDisplayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRzdHJ1X3RlYW1fYXBwbHlfcGxheWVyX2Rpc3BsYXkucHJvdG8SBnpwcm90",
            "bxoWc3RydV9hdmF0YXJfaW5mby5wcm90byK0AgoWVGVhbUFwcGx5UGxheWVy",
            "RGlzcGxheRIWCgZjaGFySWQYASABKANSBmNoYXJJZBISCgRuYW1lGAIgASgJ",
            "UgRuYW1lEhoKCHRhbGVudElkGAMgASgFUgh0YWxlbnRJZBIyCgphdmF0YXJJ",
            "bmZvGAQgASgLMhIuenByb3RvLkF2YXRhckluZm9SCmF2YXRhckluZm8SHgoK",
            "ZmlnaHRQb2ludBgFIAEoA1IKZmlnaHRQb2ludBImCg5zZWFzb25TdHJlbmd0",
            "aBgGIAEoBVIOc2Vhc29uU3RyZW5ndGgSIgoMcHJvZmVzc2lvbklkGAcgASgF",
            "Ugxwcm9mZXNzaW9uSWQSFgoGZ2VuZGVyGAggASgFUgZnZW5kZXISGgoIYm9k",
            "eVNpemUYCSABKAVSCGJvZHlTaXplYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruAvatarInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.TeamApplyPlayerDisplay), global::Zproto.TeamApplyPlayerDisplay.Parser, new[]{ "CharId", "Name", "TalentId", "AvatarInfo", "FightPoint", "SeasonStrength", "ProfessionId", "Gender", "BodySize" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TeamApplyPlayerDisplay : pb::IMessage<TeamApplyPlayerDisplay>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeamApplyPlayerDisplay> _parser = new pb::MessageParser<TeamApplyPlayerDisplay>(() => new TeamApplyPlayerDisplay());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeamApplyPlayerDisplay> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruTeamApplyPlayerDisplayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamApplyPlayerDisplay() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamApplyPlayerDisplay(TeamApplyPlayerDisplay other) : this() {
      charId_ = other.charId_;
      name_ = other.name_;
      talentId_ = other.talentId_;
      avatarInfo_ = other.avatarInfo_ != null ? other.avatarInfo_.Clone() : null;
      fightPoint_ = other.fightPoint_;
      seasonStrength_ = other.seasonStrength_;
      professionId_ = other.professionId_;
      gender_ = other.gender_;
      bodySize_ = other.bodySize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeamApplyPlayerDisplay Clone() {
      return new TeamApplyPlayerDisplay(this);
    }

    /// <summary>Field number for the "charId" field.</summary>
    public const int CharIdFieldNumber = 1;
    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { return charId_; }
      set {
        charId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "talentId" field.</summary>
    public const int TalentIdFieldNumber = 3;
    private int talentId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TalentId {
      get { return talentId_; }
      set {
        talentId_ = value;
      }
    }

    /// <summary>Field number for the "avatarInfo" field.</summary>
    public const int AvatarInfoFieldNumber = 4;
    private global::Zproto.AvatarInfo avatarInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.AvatarInfo AvatarInfo {
      get { return avatarInfo_; }
      set {
        avatarInfo_ = value;
      }
    }

    /// <summary>Field number for the "fightPoint" field.</summary>
    public const int FightPointFieldNumber = 5;
    private long fightPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FightPoint {
      get { return fightPoint_; }
      set {
        fightPoint_ = value;
      }
    }

    /// <summary>Field number for the "seasonStrength" field.</summary>
    public const int SeasonStrengthFieldNumber = 6;
    private int seasonStrength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeasonStrength {
      get { return seasonStrength_; }
      set {
        seasonStrength_ = value;
      }
    }

    /// <summary>Field number for the "professionId" field.</summary>
    public const int ProfessionIdFieldNumber = 7;
    private int professionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProfessionId {
      get { return professionId_; }
      set {
        professionId_ = value;
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 8;
    private int gender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "bodySize" field.</summary>
    public const int BodySizeFieldNumber = 9;
    private int bodySize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BodySize {
      get { return bodySize_; }
      set {
        bodySize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeamApplyPlayerDisplay);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeamApplyPlayerDisplay other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharId != other.CharId) return false;
      if (Name != other.Name) return false;
      if (TalentId != other.TalentId) return false;
      if (!object.Equals(AvatarInfo, other.AvatarInfo)) return false;
      if (FightPoint != other.FightPoint) return false;
      if (SeasonStrength != other.SeasonStrength) return false;
      if (ProfessionId != other.ProfessionId) return false;
      if (Gender != other.Gender) return false;
      if (BodySize != other.BodySize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharId != 0L) hash ^= CharId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (TalentId != 0) hash ^= TalentId.GetHashCode();
      if (avatarInfo_ != null) hash ^= AvatarInfo.GetHashCode();
      if (FightPoint != 0L) hash ^= FightPoint.GetHashCode();
      if (SeasonStrength != 0) hash ^= SeasonStrength.GetHashCode();
      if (ProfessionId != 0) hash ^= ProfessionId.GetHashCode();
      if (Gender != 0) hash ^= Gender.GetHashCode();
      if (BodySize != 0) hash ^= BodySize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (TalentId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TalentId);
      }
      if (avatarInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AvatarInfo);
      }
      if (FightPoint != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(FightPoint);
      }
      if (SeasonStrength != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeasonStrength);
      }
      if (ProfessionId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ProfessionId);
      }
      if (Gender != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Gender);
      }
      if (BodySize != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(BodySize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CharId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (TalentId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TalentId);
      }
      if (avatarInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AvatarInfo);
      }
      if (FightPoint != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(FightPoint);
      }
      if (SeasonStrength != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeasonStrength);
      }
      if (ProfessionId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ProfessionId);
      }
      if (Gender != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Gender);
      }
      if (BodySize != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(BodySize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (TalentId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TalentId);
      }
      if (avatarInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AvatarInfo);
      }
      if (FightPoint != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FightPoint);
      }
      if (SeasonStrength != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeasonStrength);
      }
      if (ProfessionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProfessionId);
      }
      if (Gender != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gender);
      }
      if (BodySize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BodySize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeamApplyPlayerDisplay other) {
      if (other == null) {
        return;
      }
      if (other.CharId != 0L) {
        CharId = other.CharId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.TalentId != 0) {
        TalentId = other.TalentId;
      }
      if (other.avatarInfo_ != null) {
        if (avatarInfo_ == null) {
          AvatarInfo = new global::Zproto.AvatarInfo();
        }
        AvatarInfo.MergeFrom(other.AvatarInfo);
      }
      if (other.FightPoint != 0L) {
        FightPoint = other.FightPoint;
      }
      if (other.SeasonStrength != 0) {
        SeasonStrength = other.SeasonStrength;
      }
      if (other.ProfessionId != 0) {
        ProfessionId = other.ProfessionId;
      }
      if (other.Gender != 0) {
        Gender = other.Gender;
      }
      if (other.BodySize != 0) {
        BodySize = other.BodySize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            TalentId = input.ReadInt32();
            break;
          }
          case 34: {
            if (avatarInfo_ == null) {
              AvatarInfo = new global::Zproto.AvatarInfo();
            }
            input.ReadMessage(AvatarInfo);
            break;
          }
          case 40: {
            FightPoint = input.ReadInt64();
            break;
          }
          case 48: {
            SeasonStrength = input.ReadInt32();
            break;
          }
          case 56: {
            ProfessionId = input.ReadInt32();
            break;
          }
          case 64: {
            Gender = input.ReadInt32();
            break;
          }
          case 72: {
            BodySize = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CharId = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            TalentId = input.ReadInt32();
            break;
          }
          case 34: {
            if (avatarInfo_ == null) {
              AvatarInfo = new global::Zproto.AvatarInfo();
            }
            input.ReadMessage(AvatarInfo);
            break;
          }
          case 40: {
            FightPoint = input.ReadInt64();
            break;
          }
          case 48: {
            SeasonStrength = input.ReadInt32();
            break;
          }
          case 56: {
            ProfessionId = input.ReadInt32();
            break;
          }
          case 64: {
            Gender = input.ReadInt32();
            break;
          }
          case 72: {
            BodySize = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
