// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_create_team_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_create_team_request.proto</summary>
  public static partial class StruCreateTeamRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_create_team_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruCreateTeamRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zdHJ1X2NyZWF0ZV90ZWFtX3JlcXVlc3QucHJvdG8SBnpwcm90bxodZW51",
            "bV9lX3RlYW1fbWVtYmVyX3R5cGUucHJvdG8i7AIKEUNyZWF0ZVRlYW1SZXF1",
            "ZXN0EhYKBmNoYXJJZBgCIAEoA1IGY2hhcklkEhoKCHRhcmdldElkGAMgASgN",
            "Ugh0YXJnZXRJZBIgCgtpc0F1dG9NYXRjaBgEIAEoCFILaXNBdXRvTWF0Y2gS",
            "IgoMaXNTaG93SW5IYWxsGAUgASgIUgxpc1Nob3dJbkhhbGwSPwoOdGVhbU1l",
            "bWJlclR5cGUYBiABKA4yFy56cHJvdG8uRVRlYW1NZW1iZXJUeXBlUg50ZWFt",
            "TWVtYmVyVHlwZRJSCg1qb2luQ29uZGl0aW9uGAcgAygLMiwuenByb3RvLkNy",
            "ZWF0ZVRlYW1SZXF1ZXN0LkpvaW5Db25kaXRpb25FbnRyeVINam9pbkNvbmRp",
            "dGlvbhISCgRkZXNjGAggASgJUgRkZXNjGjQKEkpvaW5Db25kaXRpb25FbnRy",
            "eRILCgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAM6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.EnumETeamMemberTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.CreateTeamRequest), global::Zproto.CreateTeamRequest.Parser, new[]{ "CharId", "TargetId", "IsAutoMatch", "IsShowInHall", "TeamMemberType", "JoinCondition", "Desc" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CreateTeamRequest : pb::IMessage<CreateTeamRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateTeamRequest> _parser = new pb::MessageParser<CreateTeamRequest>(() => new CreateTeamRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreateTeamRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruCreateTeamRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateTeamRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateTeamRequest(CreateTeamRequest other) : this() {
      charId_ = other.charId_;
      targetId_ = other.targetId_;
      isAutoMatch_ = other.isAutoMatch_;
      isShowInHall_ = other.isShowInHall_;
      teamMemberType_ = other.teamMemberType_;
      joinCondition_ = other.joinCondition_.Clone();
      desc_ = other.desc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreateTeamRequest Clone() {
      return new CreateTeamRequest(this);
    }

    /// <summary>Field number for the "charId" field.</summary>
    public const int CharIdFieldNumber = 2;
    private long charId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CharId {
      get { return charId_; }
      set {
        charId_ = value;
      }
    }

    /// <summary>Field number for the "targetId" field.</summary>
    public const int TargetIdFieldNumber = 3;
    private uint targetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "isAutoMatch" field.</summary>
    public const int IsAutoMatchFieldNumber = 4;
    private bool isAutoMatch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAutoMatch {
      get { return isAutoMatch_; }
      set {
        isAutoMatch_ = value;
      }
    }

    /// <summary>Field number for the "isShowInHall" field.</summary>
    public const int IsShowInHallFieldNumber = 5;
    private bool isShowInHall_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsShowInHall {
      get { return isShowInHall_; }
      set {
        isShowInHall_ = value;
      }
    }

    /// <summary>Field number for the "teamMemberType" field.</summary>
    public const int TeamMemberTypeFieldNumber = 6;
    private global::Zproto.ETeamMemberType teamMemberType_ = global::Zproto.ETeamMemberType.Five;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zproto.ETeamMemberType TeamMemberType {
      get { return teamMemberType_; }
      set {
        teamMemberType_ = value;
      }
    }

    /// <summary>Field number for the "joinCondition" field.</summary>
    public const int JoinConditionFieldNumber = 7;
    private static readonly pbc::MapField<int, long>.Codec _map_joinCondition_codec
        = new pbc::MapField<int, long>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt64(16, 0L), 58);
    private readonly pbc::MapField<int, long> joinCondition_ = new pbc::MapField<int, long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, long> JoinCondition {
      get { return joinCondition_; }
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 8;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreateTeamRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreateTeamRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CharId != other.CharId) return false;
      if (TargetId != other.TargetId) return false;
      if (IsAutoMatch != other.IsAutoMatch) return false;
      if (IsShowInHall != other.IsShowInHall) return false;
      if (TeamMemberType != other.TeamMemberType) return false;
      if (!JoinCondition.Equals(other.JoinCondition)) return false;
      if (Desc != other.Desc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CharId != 0L) hash ^= CharId.GetHashCode();
      if (TargetId != 0) hash ^= TargetId.GetHashCode();
      if (IsAutoMatch != false) hash ^= IsAutoMatch.GetHashCode();
      if (IsShowInHall != false) hash ^= IsShowInHall.GetHashCode();
      if (TeamMemberType != global::Zproto.ETeamMemberType.Five) hash ^= TeamMemberType.GetHashCode();
      hash ^= JoinCondition.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CharId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(CharId);
      }
      if (TargetId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TargetId);
      }
      if (IsAutoMatch != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsAutoMatch);
      }
      if (IsShowInHall != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsShowInHall);
      }
      if (TeamMemberType != global::Zproto.ETeamMemberType.Five) {
        output.WriteRawTag(48);
        output.WriteEnum((int) TeamMemberType);
      }
      joinCondition_.WriteTo(output, _map_joinCondition_codec);
      if (Desc.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Desc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CharId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(CharId);
      }
      if (TargetId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TargetId);
      }
      if (IsAutoMatch != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsAutoMatch);
      }
      if (IsShowInHall != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsShowInHall);
      }
      if (TeamMemberType != global::Zproto.ETeamMemberType.Five) {
        output.WriteRawTag(48);
        output.WriteEnum((int) TeamMemberType);
      }
      joinCondition_.WriteTo(ref output, _map_joinCondition_codec);
      if (Desc.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Desc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CharId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CharId);
      }
      if (TargetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TargetId);
      }
      if (IsAutoMatch != false) {
        size += 1 + 1;
      }
      if (IsShowInHall != false) {
        size += 1 + 1;
      }
      if (TeamMemberType != global::Zproto.ETeamMemberType.Five) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TeamMemberType);
      }
      size += joinCondition_.CalculateSize(_map_joinCondition_codec);
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreateTeamRequest other) {
      if (other == null) {
        return;
      }
      if (other.CharId != 0L) {
        CharId = other.CharId;
      }
      if (other.TargetId != 0) {
        TargetId = other.TargetId;
      }
      if (other.IsAutoMatch != false) {
        IsAutoMatch = other.IsAutoMatch;
      }
      if (other.IsShowInHall != false) {
        IsShowInHall = other.IsShowInHall;
      }
      if (other.TeamMemberType != global::Zproto.ETeamMemberType.Five) {
        TeamMemberType = other.TeamMemberType;
      }
      joinCondition_.MergeFrom(other.joinCondition_);
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            CharId = input.ReadInt64();
            break;
          }
          case 24: {
            TargetId = input.ReadUInt32();
            break;
          }
          case 32: {
            IsAutoMatch = input.ReadBool();
            break;
          }
          case 40: {
            IsShowInHall = input.ReadBool();
            break;
          }
          case 48: {
            TeamMemberType = (global::Zproto.ETeamMemberType) input.ReadEnum();
            break;
          }
          case 58: {
            joinCondition_.AddEntriesFrom(input, _map_joinCondition_codec);
            break;
          }
          case 66: {
            Desc = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            CharId = input.ReadInt64();
            break;
          }
          case 24: {
            TargetId = input.ReadUInt32();
            break;
          }
          case 32: {
            IsAutoMatch = input.ReadBool();
            break;
          }
          case 40: {
            IsShowInHall = input.ReadBool();
            break;
          }
          case 48: {
            TeamMemberType = (global::Zproto.ETeamMemberType) input.ReadEnum();
            break;
          }
          case 58: {
            joinCondition_.AddEntriesFrom(ref input, _map_joinCondition_codec);
            break;
          }
          case 66: {
            Desc = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
